### ISSUE TITLE
Using yml files for parameters instead of modules

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#10]
There are two modules (corsika_parameters.py and model_parameters.py) that should become yml files in data/parameter-files.

**Comment by orelgueta** [comment]
corsika_parameters.py is done already, model_parameters.py might actually go into the DB (though I am not even sure why it's needed). I will assign myself and take a look.

**Comment by orelgueta** [comment]
The type can be read from the DB (I actually have a TODO in the code to make it even simpler). However, the name validation of the parameter cannot be done from the DB unfortunately. 

What I suggest to do then is to change the type validation to get the type from the DB. Then I would move the name validation to `names.py` and keep only the parameters that might need to change their name like `trigger_pixels - trigger_pixel`, `telescope_transmission - telescope_trans`, etc. That would make the list shorter and I guess it fits well with the idea of `names.py`

What do you think?

**Comment by GernotMaier** [comment]
Agree, sounds good!

**Comment by GernotMaier** [comment]
Agree.

And are we sure that we want to keep the functionality of building a model from the simtel configuratinon. It sounds nice, but do we have a use case for it?

**Comment by orelgueta** [comment]
Yes, I could see a use case for it. For example, someone has already a model they run without gammasim-tools and they want to test it. It's rare, but I would keep it. I don't want to put effort in it though because, as you say, it's not really an important use case.
