### ISSUE TITLE
LST mirror list missing in the DB

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#107]
LST mirror list mirror_CTA-N-LST2_v2020-04-07.dat cannot be found in the database.
From the reports, we should be using mirror_CTA-S-LST2_v2020-04-07.dat.

**Comment by orelgueta** [comment]
I can add this file manually, but instead I am trying to think of a way to write such functionality into gammasim_tools. Let's say I write a simple function that uploads a list of files to the DB, where should the user put those files to be uploaded? Is there a natural place for it in the current directory structure?

**Comment by RaulRPrado** [comment]
> I can add this file manually, but instead I am trying to think of a way to write such functionality into gammasim_tools. Let's say I write a simple function that uploads a list of files to the DB, where should the user put those files to be uploaded? Is there a natural place for it in the current directory structure?

Can't we ask for the file path?

**Comment by orelgueta** [comment]
File is uploaded using the functionality in #161, closing.
