### ISSUE TITLE
Separate reading parameters from writing files in the db_handler

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#109]
By now the function getModelParameters reads the list of parameters and, in the background, writes the files out.
We would better separate these two steps.
In the TelescopeModel, the files should be written out only when calling the exportConfigFile function, not whe building the list of parameters.

**Comment by orelgueta** [comment]
I agree that it should be written out only when you call exportConfigFile. I am not sure how to implement it though. It means that TelescopeModel will have to keep the list of files (or rebuilt it by going over the parameters again) and provide to the configuration exporter. Then the exporter will have to call the db_handler. Probably that could be done.

Who should work on it depends on the urgency. I don't think I will be able to implement it in the next few weeks, if it can wait, then I can do it.

**Comment by RaulRPrado** [comment]
> I agree that it should be written out only when you call exportConfigFile. I am not sure how to implement it though. It means that TelescopeModel will have to keep the list of files (or rebuilt it by going over the parameters again) and provide to the configuration exporter. Then the exporter will have to call the db_handler. Probably that could be done.
> 
> Who should work on it depends on the urgency. I don't think I will be able to implement it in the next few weeks, if it can wait, then I can do it.

I think the db_handler should provide a method to write a single file into a specific directory and then we can go over all parameters of TelescopeModel and write them out. The TelescopeModel is storing the parameters with the same structure as they come out of the DB, so we have the flags isFile and Applicable available.
This should all be done by the TelescopeModel, not by the SimtelConfigWriter.

I can probably work on that soon. But I wanted to give you the chance in case you have the time.

**Comment by orelgueta** [comment]
Yes, this is similar to what I would like to do for the LST file missing in #107. I will try to do it at some point in the next couple of weeks, but if it is urgent and you want to do it yourself, no problem.

**Comment by RaulRPrado** [comment]
Ok, I will work on this soon, while I want for the PR that I opened today.
