### ISSUE TITLE
GetOutputDirectory changed

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#11]
https://github.com/gammasim/gammasim-tools/blob/669da4824fc31b9aef1df23b34e127812dabb1fa/simtools/simtel_runner.py#L107

This function does not exist anymore. Noticed when trying to fix #7 when test failed.

**Comment by RaulRPrado** [comment]
Sorry, my bad. Fixed with https://github.com/gammasim/gammasim-tools/commit/7685926bf84e72a6940f1edf7107b391f3a7b831 on the master branch. Please, merge it to your branch.

**Comment by orelgueta** [comment]
Thanks, but now I get a different error for "isRayTracingMode" which doesn't exist anymore.
For the record, I am not using my branch, I am using the master just so that I can fix and close #7.

**Comment by RaulRPrado** [comment]
Give me a minute

**Comment by orelgueta** [comment]
Take as much time as you want, this is not urgent at all!

**Comment by RaulRPrado** [comment]
Done.
pytest all PASSED at the master now.
Thanks for spotting these bugs.
