### ISSUE TITLE
Setup automatic testing using GitHub Actions

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#112]
This is a first prototype of some automatic testing using GitHub actions. 

Setup your local testing environment: https://github.com/gammasim/gammasim-tools/wiki/Github-Actions

First example is installing gammasim-tools and run pytest; example file in:

```
.github/workflows/python-tests.yml
```

**Comment by GernotMaier** [comment]
Seems to work (apart from that pytest fails):
https://github.com/gammasim/gammasim-tools/runs/2276658626

**Comment by RaulRPrado** [comment]
Most of the pytest failures are related to not finding the config.yml file.

We have to create a config.yml file during the action. Still, we will have problems to access the DB.
I wouldn't know how to fix that. There could be a way to select only a fraction of the test modules to be run by pytest. But I don't think that would make sense, since we wouldn't be testing the whole package properly.

**Comment by GernotMaier** [comment]
For the DB, having a readonly access should work, as we discussed earlier.

We can save authentication details for GitHubActions in the github preference, so that they are not visible to anyone.

**Comment by GernotMaier** [comment]
Some minor updates to the continuous integration steps:

- efficiency improvement in workflow and using mamba (so much faster than conda installation).
- (disabled pyTest, until we solved the DB issue)
- add simple pyFlakes test for python errors (note that there are actually some errors)

For the new year, we should try and manage run pytest:
- the integration of the DB: maybe by introducing a read-only account
- download and compile corsika7.7_simtelarray.tar.gz (similar to docker preparation; should be straight forward)

**Comment by GernotMaier** [comment]
Is it correct that the only point not implemented yet is to allow the unit tests to use the database? What was the reason for not adding this?

Read access should be possible by using the secrets DB_READ_NAME, DB_READ_USER, DB_READ_PW

**Comment by RaulRPrado** [comment]
That seems correct. I thought you were doing that, but I can do it.

**Comment by GernotMaier** [comment]
I can do it - we simply prepare a `dbDetails.yml` with the secrets, or?

**Comment by RaulRPrado** [comment]
I am working on it. It is similar to what I did with the sim tel array

**Comment by GernotMaier** [comment]
Added with PR #212
