### ISSUE TITLE
Update sim_telarray tarball

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#1152]
The `testeff` software was updated. Once the new version is included in the tarball, we should update the tarball used to build the containers. I assign it to myself to keep track of the tarball availability, but @GernotMaier will actually update the tarball on his DESY space.

**Comment by orelgueta** [comment]
It would be nice to get it from gitlab, yes. Maybe we take a quick look and see if it's easy. If it isn't we push it for the next maintenance period.

**Comment by GernotMaier** [comment]
Looking at it:

- the gitlab is only sim_telarray, not the package for corsika/sim_telarray. I don't know how easy it would be to change our current workflow which assumes that both are in the same package
- gitlab allows to download the package as [tar file](https://gitlab.cta-observatory.org/Konrad.Bernloehr/sim_telarray/-/archive/master/sim_telarray-master.tar.gz), so this is not an issue. KB also updates the gitlab (but we would need a token to access the repository, as it is private)

**Comment by orelgueta** [comment]
> * the gitlab is only sim_telarray, not the package for corsika/sim_telarray. I don't know how easy it would be to change our current workflow which assumes that both are in the same package

It's probably not too bad because the tarball we will get from sim_telarray will just replace the sim_telarray tarball of the usual corsika/sim_telarray tarball that we download from Konrad's website. It means we won't keep up with changes to e.g., eventio, but that we can do manually since those are rare.

So the workflow would probably remain as it is, except we will also download the tarball from gitlab and replace the sim_telarray tar package with this one. We would also have to delete the cfg directory (which we also do now).

> * gitlab allows to download the package as [tar file](https://gitlab.cta-observatory.org/Konrad.Bernloehr/sim_telarray/-/archive/master/sim_telarray-master.tar.gz), so this is not an issue. KB also updates the gitlab (but we would need a token to access the repository, as it is private)

The fact is private is why I couldn't find it before and look into it myself. I guess it is private because of the telescope models, but I am not sure it is relevant anymore since we published them. Maybe it's worth asking Konrad about making it public.

**Comment by orelgueta** [comment]
A new tarball is available that includes the required change to testeff.c:

https://www.mpi-hd.mpg.de/hfm/CTA/MC/Software/Testing/corsika7.7_simtelarray.tar.gz
