### ISSUE TITLE
Use a dict or yaml file system to pass in arguments in classes instead of kwargs

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#116]
Some classes, like RayTracing, are receiving arguments through kwargs.
These have to be changed to receive arguments with the dict or yaml file system, used in ArrayModel, for example.

**Comment by kosack** [comment]
I'd suggest always supporting both, so you can construct the class like:
```py3
instance = MyClass(param1=x, param2=y)
instance = MyClass(**config_dict["MyClassParams"])
```

and ideally have that second way be a constructor like:
```py3
instance = MyClass.from_config(config_dict)
```
That is what we do in ctapipe - all classes be default are constructed with keyword args, but we provide speclialized constructors that do it from a string, config file, etc.

**Comment by RaulRPrado** [comment]
Thanks for the comments.
I changed the system in order to allow for all the options, consistently. We now have by default a system that accepts a dict or a yaml file as arguments and all the classes have a classmethod to built it from kwargs. 
I think that makes more sense because we have some classes with long lists of configurable parameters, so users may often want to store them in yaml files for the sake of reusability.
