### ISSUE TITLE
Make telescope model names consistent all over the modules

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#118]
At the moment, there are two patterns for the telescope names, with and without site as part of the name.
telescope_model receives the telescope name as North-LST-1 while other modules receive site separately and only LST-1 as telescope name.

Additionally, a distinction has to be made between "telescope model name" (in the model related modules) and the "telescope name" used by the layout module (L-01, M-05).

**Comment by GernotMaier** [comment]
I think we can wait with that until we get 'official' names from CTAO. These are apparently in preparation, but I don't know when they are released.

**Comment by RaulRPrado** [comment]
The names themselves do not matter here. The issue was related to the patterns, specially about the telescope model names.

It was fixed in #129
