### ISSUE TITLE
Handling of missing parameters and usage of default values

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#124]
Are we happy with the sim_telarrary approach of use 'default values' when parameters are not specified? There are also good reasons to require all parameters to be specified (see recent issues with prod5 simulations).

**Comment by RaulRPrado** [comment]
There are two different contexts here:

a) sim_telarray using default parameters for telescopes that are not configured individually.

b) having a set of default parameters for CORSIKA configuration (the issue from the PR).

About b), I don't think the alternative is a good option. Most of the CORSIKA parameters will not be changed regularly. We can't expect the user to set all of them every time. Why would someone change the energy threshold of all types of particles regularly, for example? 

The code has been designed to allow the user to set these parameters easily, at any time. But this is expected to happen only in case of specific studies. 
Requesting these parameters to be set every time is very harmful for usability.

**Comment by GernotMaier** [comment]
But shouldn't default parameters be in the data base? Although I am not sure if we ever discussed if we want to have the CORSIKA parameters also in the database. My feeling is that it is better to have parameters not in the code but outside of it (e.g., in the DB or in configuration files).

**Comment by RaulRPrado** [comment]
> But shouldn't default parameters be in the data base? Although I am not sure if we ever discussed if we want to have the CORSIKA parameters also in the database. My feeling is that it is better to have parameters not in the code but outside of it (e.g., in the DB or in configuration files).

Sure, we can move these parameters to the DB any time.
That is exactly why they are not 'in the code', they are in external yaml files. They are in the repository, but not in the code.

 This is a point for discussion: do we want to use the model parameter DB for that, or another one?

**Comment by GernotMaier** [comment]
DB or configuration files. But I strongly oppose having default parameters for the simulation software in the code.
