### ISSUE TITLE
Testing application produce_array_config

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#126]
Very minor comments on running the following application:

```
python applications/produce_array_config.py --label test --array_config         data/test-data/arrayConfigTest.yml -v DEBU
```
What does the following remark mean at the end of the execution? 
```
Common parameters are hardcoded!
```
I am not sure what 'common parameters' mean, are the the same parameters as we discussed separately?

At the beginning, it is difficult to understand what the following printout means:
```
crs_local cannot be built because center lon and lat are missing
crs_utm cannot be built because center lon and lat are missing
crsLocal is None - convertions will be impacted
crsUtm is None - convertions will be impacted
CORSIKA convertions cannot be done - missing obs level and/or sphere center
```

Very minor: on the [documentation website](https://gammasim.github.io/gammasim-tools/applications.html#make-regular-array), the number of spaces in the yellow box for the application command line is not consistent between all arguments.

**Comment by RaulRPrado** [comment]
> 
> What does the following remark mean at the end of the execution?
> 
> ```
> Common parameters are hardcoded!
> ```
> 
> I am not sure what 'common parameters' mean, are the the same parameters as we discussed separately?

This comes from simtel-config-writer. sim_telarray needs a set a parameters that are common to all telescopes. We should somehow store these in the model parameter DB. Maybe we could create a telescope model named 'Common'. This has to be discussed with @orelgueta. Meanwhile, the warning is meaningful.


> At the beginning, it is difficult to understand what the following printout means:
> 
> ```
> crs_local cannot be built because center lon and lat are missing
> crs_utm cannot be built because center lon and lat are missing
> crsLocal is None - convertions will be impacted
> crsUtm is None - convertions will be impacted
> CORSIKA convertions cannot be done - missing obs level and/or sphere center
> ```

This comes from the layout module. These warning are meaninful, they just should happen if one is using the pre-defined layout correctly. I need to investigate this. Let's keep it open meanwhile.


> Very minor: on the [documentation website](https://gammasim.github.io/gammasim-tools/applications.html#make-regular-array), the number of spaces in the yellow box for the application command line is not consistent between all arguments.

This was fixed in the simtel-config-writer branch. Apparently you can't use \ to break lines within code-block.

**Comment by GernotMaier** [comment]
Putting a warning related to this issue is fine for me, it is just that probably none except you understands exactly what 'Common parameters are hardcoded' means. Maybe say more explicitly that this is related to sim-telarray writer issues.

**Comment by RaulRPrado** [comment]
But this should be written in the log message.
The logger should automatically write the module where the message comes from, so we shouldn't need to worry about being too specific in the message.

**Comment by RaulRPrado** [comment]
Ok, I see the problem. We are not configuring the log format in the applications.
We used to do it in every application, but now I have to find a best way to do that once for all of them.
I will have a look and fix this.

**Comment by RaulRPrado** [comment]
To clarify, we should have something like this somewhere:

logging.basicConfig(format='%(levelname)s::%(module)s(l%(lineno)s)::%(funcName)s::%(message)s')

**Comment by orelgueta** [comment]
> This comes from simtel-config-writer. sim_telarray needs a set a parameters that are common to all telescopes. We should somehow store these in the model parameter DB. Maybe we could create a telescope model named 'Common'. This has to be discussed with @orelgueta. Meanwhile, the warning is meaningful.

The default parameters are already stored in the DB per telescope (under the version "default"). However, I don't think those should be our default parameters (those are HESS ones or even older). Maybe we should come up with a new set of default parameters as you say and even replace the old defaults. This should probably go in a different issue though.

**Comment by GernotMaier** [comment]
@orelgueta  - looking through this old issue, it seems that all has been addressed with the exception of the question what our default parameters are - those currently hard coded in [COMMON_PARS](https://github.com/gammasim/gammasim-tools/blob/b25d2645182a471fc1604d23d2acc70508e4c012/simtools/simtel/simtel_config_writer.py#L49).

Suggest therefore to close this issue and start a new one discussing the common parameters (otherwise I will read through all of the every couple of weeks).

**Comment by orelgueta** [comment]
I will open a new issue to fix this, we definitely shouldn't have common parameters.
