### ISSUE TITLE
testeff cannot deal with 2D camera filters or mirror reflectivity

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#128]
camera_efficiency has to replace the camera_filter and mirror_reflectivity files by average ones for ASTRI telescopes because testeff can only handle 1D files.

This has to be fixed in texteff, of by writing a tools to turn the 2D files into 1D on the fly.

**Comment by orelgueta** [comment]
We can't convert 2D to 1D files without prior information. In order to produce the 1D version the ASTRI team had to run a ray-tracing simulation to derive the average incidence angle and its reflectivity.

**Comment by RaulRPrado** [comment]
Ok.

Another option could be adding the 1D averaged files as an extra parameter of the model.
This way we could just check if it is a 2D file, and if yes, we grab the averaged one from the same telescope. We don't need to know which telescope it is.
What do you think?

**Comment by orelgueta** [comment]
I am not sure. It means we export the complexity into the model. The model itself already contains both options (i.e., older versions of the reflectivity were 1D) and sim_telarray detects automatically if it's 1D or 2D. Your suggestion would be moving a step back.
Currently the issue is that you check if the telescope is ASTRI? Would it help if instead you check if the file is 2D (it starts with RPOL or something similar)?

**Comment by RaulRPrado** [comment]
> I am not sure. It means we export the complexity into the model. The model itself already contains both options (i.e., older versions of the reflectivity were 1D) and sim_telarray detects automatically if it's 1D or 2D. Your suggestion would be moving a step back.

We are already doing that, but in a very ugly way. We set the new averaged file by hand, with its name hardcoded.
In my suggestion, we make the model more complex but at least we keep each version of the model consistent. Moving between model versions doesn't seem a good option either.

> Currently the issue is that you check if the telescope is ASTRI? Would it help if instead you check if the file is 2D (it starts with RPOL or something similar)?

It's worse than that. We already check both, if it's ASTRI and if it's a 2D file. If both True, we reset the files to the averaged version, with hardcoded names. If it's only 2D, but not ASTRI, we raise an error.

**Comment by orelgueta** [comment]
I think this might be an opportunity to break from the sim_telarray dependency. 
Maybe we create a new ecsv file with a proper header that contains both 1D and 2D. Then when we read the file we convert it to sim_telarray format, 1D or 2D, depending on which application is used.
It's more work, but that is what we want to plan to do anyway for all/most files, no?

I just worry that if we introduce this to the model now, it is some sort of hack that will be there forever. I don't particularly mind doing it, I am just trying to think of ideas how to avoid it.

**Comment by RaulRPrado** [comment]
> I think this might be an opportunity to break from the sim_telarray dependency.
> Maybe we create a new ecsv file with a proper header that contains both 1D and 2D. Then when we read the file we convert it to sim_telarray format, 1D or 2D, depending on which application is used.
> It's more work, but that is what we want to plan to do anyway for all/most files, no?

Kind of. We plan to have the files in another format, but having both 1D and 2D in the same file means more work than we planned.

> I just worry that if we introduce this to the model now, it is some sort of hack that will be there forever. I don't particularly mind doing it, I am just trying to think of ideas how to avoid it.

I agree.

I still think we don't need to do anything now. We can ask Konrad to change testeff. 
For us, it's only a matter of cleaning up the code.

**Comment by orelgueta** [comment]
OK, so what should we do? I doubt Konrad will change testeff to support 2D files (I think it's a large change). 

Maybe we include in the header of the 2D file the name of the telescope and then the code can pick it up from there (so that at least you do not have to check the telescope)?
Then we can keep the 1D files in the DB and you just need to get the name of the file (either from the 2D header or from somewhere else which is not in the code).

**Comment by orelgueta** [comment]
Going back to this point, a new option has come up.

We now have the distribution of photon incidence angles on the focal plane. It was calculated by Akira for the SST and we should have one also for SCT. We can make this distribution part of the model (even if it is not used as input to sim_telarray). Then, if the file we have is a 2D file, we read this distribution, calculate the average incidence angle and extract from the 2D file the 1D distribution for that average angle (we don't really need to interpolate, the distributions are fairly flat). 

This solution would allow us to avoid hardcoding anything, should keep the versions updated automatically (though the angular distribution would probably not change) and use the correct distribution always. What do you say?

**Comment by orelgueta** [comment]
I implemented two ways of doing this. Please see the plot below with a comparison of the two methods and for reference the sim_telarray curve which Konrad calculated.

![one-dim-camera-filter-tranmission-sst](https://user-images.githubusercontent.com/22728856/196922935-0b29607b-7815-4e61-9226-15c565684a37.png)

- In the first method I calculate the average incidence angle and then interpolate the two dimensional curve to that average incidence angle. That is shown in the blue curve above.
- In the second method I simply calculate a weighted average from the two-dimensional curves, using the incidence angle curve as weights for the average. That is shown in the orange curve. This method is the same as what Konrad used for the sim_telarray curve, with the only difference that he used various off-axis angles (0-4 deg) for weights, while I used only the zero deg curve (the difference is very small). 

For the final implementation, the average method will be used. However, the interpolation method will be kept in the code in case it is useful in the future.

**Comment by GernotMaier** [comment]
Agree that the average method should be used.

The ratio is relative to sim_telarray?

**Comment by orelgueta** [comment]
Yes, the ratio is with respect to sim_telarray
