### ISSUE TITLE
Adding array_trigger to the model DB (or not)

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#152]
When trying to reproduce prod5 simulations, I found that array_trigger is not in the DB. Should we add it or not?

**Comment by orelgueta** [comment]
The files are now in the DB. A quick test worked but a more thorough test would be good. If it all works we can close.

Also, what about the name? Should we stick to array_trigger**s**?

**Comment by RaulRPrado** [comment]
Yes, array_triggers is fine by me.

**Comment by orelgueta** [comment]
OK! so I keep array_triggers and I assume the tests went OK (at least Gernot's and mine did) so I close it.
