### ISSUE TITLE
Clarify latex dependency

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#155]
Latex is required to run some tools (e.g., applications/validate_optics.py), but it is unclear which latex distribution and what packages are needed (e.g, the tool mentioned fails for me with `LaTeX Error: File `type1cm.sty' not found.`).

Do you want to clarify this? Should latex be part of the conda environment, so that we don't depend on whatever system installation is available?

**Comment by GernotMaier** [comment]
It is certainly a very heavy dependency - for ubuntu it requires to install texlive-full which is 5.5 GB large and essentially unusable with a docker image.

**Comment by orelgueta** [comment]
Actually for linux we can install a lightweight version with just the necessary packages. I have done it before and it doesn't come out to be that big (if I remember correctly, less than 1 GB). However, it is still a very significant dependency, which for "normal" users is unnecessary and for a docker would make it unjustifiably very heavy. 

We could potentially have two versions of the software, one for production and one for producing reports. 

But honestly I think it would make more sense to try to avoid this dependency. It would probably mean not producing the PDF reports, but perhaps that's not a bad thing.

**Comment by GernotMaier** [comment]
Agree with that.

For me the main issue right now is that we do not know what 'working latex installation' means. The [documentation page](https://matplotlib.org/stable/tutorials/text/usetex.html) does not say a lot. 

I tried several packages and one either has to install the full texlive package or (after searching on google for other people complaining) combined 800 MB version of:
```
   cm-super \
    dvipng \
    texlive-latex-extra \
    texlive-fonts-recommended
```

**Comment by orelgueta** [comment]
Yes, I have this list (a similar one anyway). Sorry, I could have saved you a bit of time by pasting it here.

Either way, I suggest we already now remove this dependency, if @RaulRPrado agrees.

**Comment by GernotMaier** [comment]
As a side note to this issue: using latex means as well that running gammasim-tools with debug level produces (at least for me) thousand of lines of latex-related debug messages. This makes it very hard to work with the debug mode.

I kind of refuse to accept that matplotlib cannot make pretty titles without latex installed.

And I think we agreed that we want to publish reports not in latex but on webpages? If we need latex, we could maybe do a simpler type of installation using conda or a docker implementation.

**Comment by orelgueta** [comment]
As I already mentioned, I vote to remove Latex all together.

**Comment by RaulRPrado** [comment]
> As I already mentioned, I vote to remove Latex all together.

Me too.

Should I remove all useTex?

**Comment by GernotMaier** [comment]
Yes (from my viewpoint).

**Comment by orelgueta** [comment]
Yes please

**Comment by GernotMaier** [comment]
Removed latex with #183
