### ISSUE TITLE
Telescope model information transfer

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#16]
https://github.com/gammasim/gammasim-tools/blob/53bc1708b979c60b61fe8e075f278235b58d2108/simtools/camera.py#L447

Instead of transferring the telescope model instance itself, I changed it to transfer two telescope parameters. Those are then expected to be obtained in the user application, like:

https://github.com/gammasim/gammasim-tools/blob/53bc1708b979c60b61fe8e075f278235b58d2108/applications/plotCamera.py#L32

@RaulRPrado, is this what you had in mind?

**Comment by RaulRPrado** [comment]
Yes, exactly.

The sub-model classes should receive minimum data (in this case only the camera_config_file and maybe focal length) and exist independently of the telescope model. The data should be "raw", meaning numbers or files directly.
All the connection with labels like telescope types, sites etc should be interfaced by TelescopeModel.

The camera class can be used standalone as in your application but we must also use it inside the TelescopeModel for the sake of modularity
TelescopeModel will have a Camera instance as a attribute, for example.

I would suggest to pass the camera_config_file as a required argument at the __init__. The idea is that a Camera instance cannot exist without a camera_config_file, so it has be given at the init level. The readPixelList can be called at the init then.

Passing focalLength at the init and keep it as an attribute would also be an idea.

pixels, neighbours and edgePixelIndices should be attributes of the class and then you would call directly calcFOV, with them being computed and used internally. You wouldn't have to get them explicitly outside and pass them back as arguments.

Please, move the camera.py module to model/camera.py.

**Comment by orelgueta** [comment]
> I would suggest to pass the camera_config_file as a required argument at the **init**. The idea is that a Camera instance cannot exist without a camera_config_file, so it has be given at the init level. The readPixelList can be called at the init then.
> 
> Passing focalLength at the init and keep it as an attribute would also be an idea.

OK, all of that sounds reasonable, will do that.


> pixels, neighbours and edgePixelIndices should be attributes of the class and then you would call directly calcFOV, with them being computed and used internally. You wouldn't have to get them explicitly outside and pass them back as arguments.

This was the original implentation, but I changed it after @GernotMaier made the last comment here:

https://github.com/gammasim/gammasim-documentation/issues/15#issuecomment-626343759

However, I might have misunderstood. Maybe it's better to simply give the telescope name and not an explicit pixel list (though I can imagine a use case for the latter as well...)

 > Please, move the camera.py module to model/camera.py.

OK

**Comment by RaulRPrado** [comment]
> > pixels, neighbours and edgePixelIndices should be attributes of the class and then you would call directly calcFOV, with them being computed and used internally. You wouldn't have to get them explicitly outside and pass them back as arguments.
> 
> This was the original implentation, but I changed it after @GernotMaier made the last comment here:
> 
> [gammasim/gammasim-documentation#15 (comment)](https://github.com/gammasim/gammasim-documentation/issues/15#issuecomment-626343759)
> 
> However, I might have misunderstood. Maybe it's better to simply give the telescope name and not an explicit pixel list (though I can imagine a use case for the latter as well...)

My comment about making pixels, neighbours and edgePixelIndices attributes is more related to how we use classes, and has nothing to do with the design of the class itself.

I don't think it's better to give the telescope name, please don't do it. This should be the job of TelescopeModel (linking a certain telescope type to the model parameters).
Look, his comment is about the application. At the application level you can read as input the telescope type as an argument, no problem. However, this doesn't have any implication on the design of the camera module itself.

Have a look at the app derive_rnda. That was my idea for applications. You know which input you need for a certain task, then you get this input from the command line and put together the library to execute it.

I actually think your application should be more specific than plotCamera. Maybe validate_camera_fov.

**Comment by orelgueta** [comment]
> I don't think it's better to give the telescope name, please don't do it. This should be the job of TelescopeModel (linking a certain telescope type to the model parameters).

What I meant is that the user provides the name of the telescope they want to plot/get the FoV of. At the moment I didn't implement it with user args (not sure it is really needed to be honest), but essentially what I expect from the user are these four lines

https://github.com/gammasim/gammasim-tools/blob/cfe2950f0e4b6218e73c2ba259c77426d1b1daed/applications/plot_camera.py#L19-L22

The rest is done by the module essentially.
What I understood previously from his comment is that he wanted an application which calculates the FoV for any pixel list, regardless of whether it is implemented in the model or not. Now I am not sure if that is correct, so I removed that option and @GernotMaier can say which is correct.
 
> I actually think your application should be more specific than plotCamera. Maybe validate_camera_fov.

You mean without plotting? Again, this is following the request from @GernotMaier. I don't mind making two separate applications, but I don't see a reason either.

Either way, I updated the code to be more or less how you suggested, would you like to take a look before I add more documentation and ask for a pull request?

**Comment by RaulRPrado** [comment]
> What I meant is that the user provides the name of the telescope they want to plot/get the FoV of. At the moment I didn't implement it with user args (not sure it is really needed to be honest), but essentially what I expect from the user are these four lines
> 
> https://github.com/gammasim/gammasim-tools/blob/cfe2950f0e4b6218e73c2ba259c77426d1b1daed/applications/plot_camera.py#L19-L22 
> The rest is done by the module essentially.
> What I understood previously from his comment is that he wanted an application which calculates the FoV for any pixel list, regardless of whether it is implemented in the model or not. Now I am not sure if that is correct, so I removed that option and @GernotMaier can say which is correct.

Ok, I see it now. This is a trick issue. I had a similiar problem with derive_rnda.

Well, we don't need to define the final form of the application now. It's going to be very easy to adapt it later for a different strategy of inputs, as long as we write the core of the code properly in the library. I would try to get to a form that we need now, like I did with the derive_rnda. 

> You mean without plotting? Again, this is following the request from @GernotMaier. I don't mind making two separate applications, but I don't see a reason either.

It can still plot.
The way I see, a workflow should be a validation, or derivation etc. For each case, we will validate or derive something using different methods. This app validates a camera layout. Plotting and calculating the FOV is only the "how" we do it. 

> Either way, I updated the code to be more or less how you suggested, would you like to take a look before I add more documentation and ask for a pull request?

Yes, I'll do that.

**Comment by RaulRPrado** [comment]
It's great.

I changed the order or the imports, just for the sake of my OCD =)
Two comments:

a) I would prefer to pass the camera file to the class, which means the full path of the file, not only the name. The cfg.findFile() should be called externally. This is important to keep these classes independent of model DB or files location. 
A random user could write its own camera file and use the class to analyze it easily.
(I still believe on the future existence of random users. At least I want to believe it ;) )

b) Do you mind renaming legendHandlers to legend_handlers?

**Comment by orelgueta** [comment]
Made all the changes, will make a PR now. 
Closing this issue.
