### ISSUE TITLE
Paranal altitude should be 2147

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#162]
https://github.com/gammasim/gammasim-tools/blob/0db4fe45ff9fefca57c6d7e14a4f12b7bf0f6ced/data/corsika/corsika_parameters.yml#L65

The Paranal altitude I see in the Prod5 configuration files is 2147m, is there a reason why this is 2150 here?

**Comment by RaulRPrado** [comment]
Fixed in #163
