### ISSUE TITLE
Allow to use sim_telarray for unit tests

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#201]
sim_telarray is installed in a docker image (at this point we are using gernotmaier/gammasim-tools-dev:v0.1.1, but this one also has the gammasim-tools environment installed and is too big).

Managed to download and simply run sim_telarray here:
https://github.com/gammasim/gammasim-tools/runs/5302623436?check_suite_focus=true

@RaulRPrado : could you give me the most trivial usage of sim_telarray, meaning running the exectutable with some config files and expect some output?

**Comment by RaulRPrado** [comment]
I would say the validate_optics application is a good test.

https://github.com/gammasim/gammasim-tools/blob/cb8280e1e88ebe209c30ecf8a9905c9194f955c1/applications/validate_optics.py#L55

**Comment by RaulRPrado** [comment]
No, wait. It is meant to be run without BD connection?

**Comment by GernotMaier** [comment]
Yes - and you can give me the command by hand (excplicity) - just want to try if it works.

**Comment by RaulRPrado** [comment]
I added a new test in test_ray_tracing for that in branch pytest-sim_telarray.

It is called test_run_no_db. If you run "pytest simtools/tests/test_ray_tracing.py" without DB, the first test should pass if sim_telarray is fine.

If you want to see the result, you can add:

if __name__ = "__main__":
    test_run_no_db()

To the end of the file and run "python simtools/tests/test_ray_tracing.py"

**Comment by GernotMaier** [comment]
I have added now the following steps:
- download corsika7.7_simtelarray.tar.gz from DESY cloud directory (should we hide this path?)
- compile corsika & simtelarray
- add a environmental variable SIMTELPATH

I am not sure what `conftest.py` is using, does it an environmental variable `simtelPath` (lower case) or does it look into one of the configuration yaml files?

**Comment by GernotMaier** [comment]
I've also added secrets to be used for the DB - @RaulRPrado, please help me where to put them

```
${{ secrets.DB_READ_NAME }}
${{ secrets.DB_READ_USER }}
${{ secrets.DB_READ_PW }}}
```

**Comment by RaulRPrado** [comment]
We could use conftest.py to create a dbDetails.py with these info.

Or @orelgueta's strategy. Are these the readonly user? Isn't it a problem to have it public?

**Comment by RaulRPrado** [comment]
I changed the conftest.py so that it adds SIMTELPATH to the dummy config file.

The way CI-test.yml is written right now, SIMTELARRAY is not set when running pytest. I will try to fix that too.

**Comment by GernotMaier** [comment]
> Or @orelgueta's strategy. Are these the readonly user? Isn't it a problem to have it public?

Yes, this is readonly. We would use github secrets, so the actual values (user name, password, db names) would be invisible for the public.

**Comment by RaulRPrado** [comment]
> > Or @orelgueta's strategy. Are these the readonly user? Isn't it a problem to have it public?
> 
> Yes, this is readonly. We would use github secrets, so the actual values (user name, password, db names) would be invisible for the public.

Ok, but this is different than what Orel suggested. He was telling us to leave a dbDetails.yml in the repo with the readonly info.

**Comment by orelgueta** [comment]
No, that's not what I said, I said that dbDetails.yml will use these secrets. When I tried it in GitLab, which I assume is similar, you simply have something like this in the config file

`mongodbServer: ${{ secrets.DB_READ_NAME }}`
`userDB: ${{ secrets.DB_READ_USER }}`
`passDB: ${{ secrets.DB_READ_PW }}}`

and it works. I suggest we do the same now.
