### ISSUE TITLE
Set the dataLocation using absolute path in config_template.yml

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#203]
Change the config_template.yml so it is possible to run it out-of-the-box from a different directory.

**Comment by RaulRPrado** [comment]
It is already possible to use environment variables in our config.yml file. This could fix our problem. @GernotMaier just need to put

dataLocation: "$GAMMASIM_DATA"

in your config file and set the GAMMASIM_DATA location before running it from another directory.
Note that GAMMASIM_PATH="(...)/gammasim-tools/data/"

The way I interpret environment variables is very simple. There can be only a single variable, starting with $. Something like $PATH/data would not work. I found [this package](https://mariakaranasou.com/pyaml_env/) that allows for more complicated patterns, even for setting default values. However, it is a small package and I am not sure whether it is a good idea in terms of maintainability. What do you think?

**Comment by orelgueta** [comment]
I don't think we should add a dependency for this, but I will let @GernotMaier voice his opinion.

**Comment by GernotMaier** [comment]
Is there no simple way in Python to resolve a path like `$PATH/data`? It doesn't need to happen on the level of the yamlfile, as the indicated package does.

**Comment by RaulRPrado** [comment]
> Is there no simple way in Python to resolve a path like `$PATH/data`? It doesn't need to happen on the level of the yamlfile, as the indicated package does.

Yes, I just found it.

We can use os.path.expandvar for that. I will implement it.
