### ISSUE TITLE
validate optics should crash after first error

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#208]
Running validate optics, I stumbled across the issue reported in #108 (ignore the title, the actual issue is different). Regardless of what the issue is, the validate_optics application should crash after the first error report from sim_telarray. There's no sense in running all off-axis angles if the first one fails due to a configuration issue.

**Comment by GernotMaier** [comment]
As a minor thing: could we agree on that our software never crashes?

**Comment by orelgueta** [comment]
Sorry, wrong wording. The application should exit, providing a meaningful error message, after the first error from sim_telarray.

**Comment by GernotMaier** [comment]
@orelgueta  - do you have an example to follow this up?
