### ISSUE TITLE
Cleanup of branches

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#209]
Would like to have clear picture which branches are still active to make sure that no open development thread is lost.

Generally:
- let's delete all merged branches (removes already half of them)
- look at the very old ones and decide if it is useful

What would be the best way to document open development in branches? Would it make sense to open a draft pull request describing for these branches to describe what the intention is?

Following branches are not ahead of master and I suggest to delete them:

- [x] https://github.com/gammasim/gammasim-tools/tree/testeff_table

Following branches are fully merged and I suggest to delete them:

- [x] https://github.com/gammasim/gammasim-tools/tree/mongodb
- [x] https://github.com/gammasim/gammasim-tools/tree/tunnel_username
- [x] https://github.com/gammasim/gammasim-tools/tree/upload_files_to_db
- [x] https://github.com/gammasim/gammasim-tools/tree/fix_db_doc_string
- [x] https://github.com/gammasim/gammasim-tools/tree/remove_ssh_tunnel
- [x] https://github.com/gammasim/gammasim-tools/tree/psf-tuning

Following branches are in development (possibly stalled)

- [x] https://github.com/gammasim/gammasim-tools/compare/docs --> active
- [x] https://github.com/gammasim/gammasim-tools/compare/calc-nsb-camera-efficiency --> active
- [x] https://github.com/gammasim/gammasim-tools/compare/comp-resources --> active (requires some conflict solving)
- [x] https://github.com/gammasim/gammasim-tools/compare/trigger-rate-simulations --> I guess this is active?
- [x] https://github.com/gammasim/gammasim-tools/tree/fixing-bug-nectarcam-pulse-shape --> don't know what the status is?
- [x] https://github.com/gammasim/gammasim-tools/tree/sites --> some development on layout plotting?

Style editing only? Cannot be merged at this point - should we delete that, as we pick up style now with CI?
- [x] https://github.com/gammasim/gammasim-tools/compare/simtel-cfg-location

I don't understand this branch?
- [x] https://github.com/gammasim/gammasim-tools/tree/gh-pages

**Comment by orelgueta** [comment]
Deleted all of my merged branches (why is not done automatically like in Gitlab?).

The `sites` branch technically is waiting for you @GernotMaier since I implemented some layout plotting there that we said we will expand once you have a chance to look at it. Because we are always too tight with time, we kept the separate layout package instead.

The rest of the branches are Raul's, he should comment.

**Comment by GernotMaier** [comment]
Do we have written up somewhere what we want to do with the site branch? I think we need to change something to better document what is the goal of branches.

**Comment by orelgueta** [comment]
No I don't think we need to do that. A branch should live a short life with a definite goal and deleted afterwords. The documentation of what we want to do development wise is in the issues. 

The site branch case is an anomaly that I am happy to delete and forget about it. When the need rises again, we can go back to it.

**Comment by RaulRPrado** [comment]
> * [ ]  https://github.com/gammasim/gammasim-tools/compare/docs --> active
> * [ ]  https://github.com/gammasim/gammasim-tools/compare/calc-nsb-camera-efficiency --> active
> * [ ]  https://github.com/gammasim/gammasim-tools/compare/comp-resources --> active (requires some conflict solving)
> * [ ]  https://github.com/gammasim/gammasim-tools/compare/trigger-rate-simulations --> I guess this is active?
> * [ ]  https://github.com/gammasim/gammasim-tools/tree/fixing-bug-nectarcam-pulse-shape --> don't know what the status is?

These are mine and they are in principle active. I will try to merge or delete them next week.


> Style editing only? Cannot be merged at this point - should we delete that, as we pick up style now with CI?
> 
> * [ ]  https://github.com/gammasim/gammasim-tools/compare/simtel-cfg-location

This I can merge and delete.

> I don't understand this branch?
> 
> * [ ]  https://github.com/gammasim/gammasim-tools/tree/gh-pages

This is where the documentation is automatically built by the CI. We do not touch it, just let it there.

**Comment by GernotMaier** [comment]
How does the documentation building works? 

I guess this is 

https://github.com/gammasim/gammasim-tools/blob/master/.github/workflows/CI-docs.yml

and it writes to a branch with all the html pages? That branch has otherwise no connection to the code base and our repository?

**Comment by RaulRPrado** [comment]
> * [ ]  https://github.com/gammasim/gammasim-tools/tree/psf-tuning

Why didn't you delete this one?

**Comment by RaulRPrado** [comment]
> How does the documentation building works?
> 
> I guess this is
> 
> https://github.com/gammasim/gammasim-tools/blob/master/.github/workflows/CI-docs.yml
> 
> and it writes to a branch with all the html pages? That branch has otherwise no connection to the code base and our repository?

That is exactly it!

**Comment by RaulRPrado** [comment]
The gh-pages thing is a pattern in github. It was done like that before when we were using Travis CI and it is done similarly now with github CI.
