### ISSUE TITLE
print all parameters?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#21]
https://github.com/gammasim/gammasim-tools/blob/d4d1597fe6875b787cb7b5fc55f12204f21eac28/simtools/model/telescope_model.py#L258

@RaulRPrado, is this intentional?

**Comment by RaulRPrado** [comment]
Nops. It a left over from a test. Fixed by https://github.com/gammasim/gammasim-tools/commit/122b1499d49bfec0ea83f9b44205a13e8e7465a7
Thanks for spotting that =)
