### ISSUE TITLE
Implement simple setting workflow

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#222]
Implement a simple setting of parameter values workflow (e.g., submission of a file with quantum efficiency values by a user).

The workflow includes:
1. submission of data and metadata by a user through an interface: simplified first approach is that user submits the metadata in yaml format and the data in ecsv format.
2. user metadata and data is validated against a reference schema validation
3. add workflow related metadata
4. apply necessary data validation and transformation checks
5. output data and metadata to be submitted to MC model database

This workflow and example metadata schema can be found [here](https://gitlab.cta-observatory.org/cta-computing/dpps/simulationpipeline/prototypes/notes/simulation-project-metadata-and-formats/-/tree/setting_workflow)

**Comment by GernotMaier** [comment]
Update on the implementation, which needs a lot more refinement. @orelgueta - please comment.

General approach:

1. Implementation in gammasim-tools is a generic setting_from_external workflow (and not specific for quantum efficiency tables) -  renamed the application to `./applications/set_modelparameter_from_external.py`

2. The configuration specific to the QE table setting is encoding in a configuration file (example [here](https://gitlab.cta-observatory.org/cta-computing/dpps/simulationpipeline/prototypes/notes/simulation-project-metadata-and-formats/-/blob/setting_workflow/quantum_efficiency/set_quantum_efficiency_from_external.config.yml))

4. This configuration can be extended by e.g., listing what kind of plotting should be done for a quick check during the setting

5. The user input consist of [metadata](https://gitlab.cta-observatory.org/cta-computing/dpps/simulationpipeline/prototypes/notes/simulation-project-metadata-and-formats/-/blob/setting_workflow/quantum_efficiency/qe_R12992-100-05b.usermeta.yml) (this is what the user would e.g., type into a web interface) and the [data tables](https://gitlab.cta-observatory.org/cta-computing/dpps/simulationpipeline/prototypes/notes/simulation-project-metadata-and-formats/-/blob/setting_workflow/quantum_efficiency/qe_R12992-100-05b.data.ecsv).

6. User input metadata is validated against a [reference schema](https://gitlab.cta-observatory.org/cta-computing/dpps/simulationpipeline/prototypes/notes/simulation-project-metadata-and-formats/-/blob/setting_workflow/SetParameterFromExternal.userinput-schema.yml): [validate_schema](https://github.com/gammasim/gammasim-tools/blob/set_quantum_efficiency_from_external/simtools/util/validate_schema.py)

7. User input data file is validated in the following:
	- check that all required axes exist
	- check that axes units are of same type and convert to unit given in config file (e.g., wavelength can be given in Angstrom, but will be converted to nm)
	- check axes ranges to inside the allowed range and cover at least the required range
	- [validate_data](https://github.com/gammasim/gammasim-tools/blob/set_quantum_efficiency_from_external/simtools/util/validate_data.py)

8. Complete the metadata with all the required fields as listed [here](https://gitlab.cta-observatory.org/cta-computing/dpps/simulationpipeline/prototypes/notes/simulation-project-metadata-and-formats/-/blob/setting_workflow/SetParameterFromExternal.metadata-schema.yml)
	- this is where the code is most incomplete; need to revisit the metadata discussion to make this consistent.

9. Write two files which should be ready for the submission to the database: a metadata file and a data file

10. Unit tests are certainly incomplete.

Random questions:
1. is there a way to retrieve in the code the gammasim-tools software version? Use same approach as [ctapipe](https://github.com/cta-observatory/ctapipe/blob/901c7889fada9c11f8cdfd5aea324af7b8b96997/ctapipe/version.py)
2. What file name should the output model name get? I think at this point we almost always used the same name as received from the telescope teams (e.g., `qe_R12992-100-05c.dat`). Should that be a user input?
3. Not sure at all about the python file name. Should the file name be the class name? At this point it is not.

**Comment by orelgueta** [comment]
Generally it all sounds very good.

> renamed the application to `./applications/set_modelparameter_from_external.py`

Shouldn't there be an underscore between `model` and `parameter`?

> 1. is there a way to retrieve in the code the gammasim-tools software version? Use same approach as [ctapipe](https://github.com/cta-observatory/ctapipe/blob/901c7889fada9c11f8cdfd5aea324af7b8b96997/ctapipe/version.py)

As far as I know, we need to implement the conda/pip installation for that to work. I don't think it can be done without it. 

> 2. What file name should the output model name get? I think at this point we almost always used the same name as received from the telescope teams (e.g., qe_R12992-100-05c.dat). Should that be a user input?

Let's make it a user input, with the original name used as default. We should also add a check that the name does not already exist in the DB. I can add a function to the DB handler API for it if you think it's a good idea.

> 3. Not sure at all about the python file name. Should the file name be the class name? At this point it is not.

The python file name is not exactly the class name. The class names are written in PascalCase while the file names are in snake_case. The actual name should be similar, but doesn't have to be the same. Would be good to keep the name as informative as possible.

**Comment by GernotMaier** [comment]
Last update is the implementation of the PRODUCT:ASSOCIATION field:

- a list of telescopes for which the simulation model file can be used for
- PRODUCT:ASSOCIATION:ID is derived using the functionality in names.py

The two missing items before issuing a pull request now is to improve the data validation and expand the examples of data transformations:
- remove duplicates
- introduce sorting order (e.g., that wavelengths are always increasing)

Anything else we want to include into this first version? @orelgueta

**Comment by orelgueta** [comment]
No, I think that will already be enough. 

The only thing we might want to do already is check if the file name is already in the DB. We can wait with it for the second version, just like with the telescope IDs, but I don't mind implementing it now if you wish.

**Comment by GernotMaier** [comment]
I would prefer to have anything with data base in a second version.

**Comment by orelgueta** [comment]
OK!
