### ISSUE TITLE
Allow user to set logging level?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#23]
https://github.com/gammasim/gammasim-tools/blob/e5105c0b31b8365647252c44642a7783ac203cb5/applications/derive_mirror_rnda.py#L25

I have a small piece of code that allows users to set the logging level (see below, ignore the color logger calls). If you approve of it, I will add something similar to the general utils. 

```
def getLogLevelFromUser(self, logLevel):

        possibleLevels = {'info': logging.INFO,
                          'debug': logging.DEBUG,
                          'warn': logging.WARNING,
                          'warning': logging.WARNING,
                          'error': logging.ERROR,
                          'critical': logging.CRITICAL}
        logLevelLower = logLevel.lower()
        if logLevelLower not in possibleLevels:
            self.logStdout.error([['wb', 'Requested log level,'],
                                  ['r', logLevel],
                                  ['wb', ', is not known. Using INFO level instead.']])
        else:
            return possibleLevels[logLevelLower]
```

Not sure if we will add the colour logger itself to the code. I really like it and I think it helps the clarity of the output a lot, but it requires a little bit of learning how to use it, defining colour standards and adds an additional level of complexity. In my opinion it is worth it, but I won't force it in any way.

**Comment by RaulRPrado** [comment]
Sounds good, but I can't understand how it works. You could implement it in util.general and I can have a look at an example.

I don't think the coloured logger is necessary. The std logging works so well and it's so simple.

**Comment by orelgueta** [comment]
OK, I will assign myself and implement it when I get a chance. It's very simple anyway.

**Comment by orelgueta** [comment]
@RaulRPrado Can you please check out 5097b36 and tell me if this resolves this issue and I can do a PR?

**Comment by RaulRPrado** [comment]
Looks good! I left few comments there.

**Comment by orelgueta** [comment]
OK, I made the pull request, but I will leave this issue open until we fix all other loggers in the code (I can do it, no problem).

**Comment by RaulRPrado** [comment]
Ok, great.
It's better to create a new issue for the logger in other classes and close this one.

**Comment by orelgueta** [comment]
Are issues attached to classes? I didn't know that. I simply use it as a reminder to do it =)

**Comment by RaulRPrado** [comment]
No no. I didn't mean that.

I meant to create another issue for fixing the other classes instead of using this one.

**Comment by orelgueta** [comment]
Oh, OK, sure. I will close this and open a new one.
