### ISSUE TITLE
Modify the DB unit tests to separate sandboxes

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#231]

**Comment by GernotMaier** [comment]
Related to failure of tests, e.g., in https://github.com/gammasim/gammasim-tools/runs/6207829144?check_suite_focus=true

Temporary fix: reduce testing matrix for python versions to one version only.

**Comment by GernotMaier** [comment]
I have not seen this issue since a long time and I think we can close it. @orelgueta ?

**Comment by orelgueta** [comment]
But I thought you haven't  seen the issue because you now only test one python version. Do we want to abandon this idea of using a dummy DB and always require DB connection?

**Comment by GernotMaier** [comment]
A large part, maybe even the majority of the tests are skipped without a DB connection. Some also need input from the DB, and I think it would be really a big effort to replace this all by dummy DB and entries. I would rather see our DB access a bit more robust so that it can handle more connections simultaneously.

**Comment by orelgueta** [comment]
OK, I agree with you, we should assume the DB is always available (if internet connection is available). Once comment though is that it's not the robustness of the connection which is the issue, it is that some of the tests write and read from a sandbox DB. If one test clears the sandbox while another one is writing to it, we get that error you saw in the past. I will try to come up with a different way of doing things so it doesn't happen, but it's less urgent now so let's close this issue and open a new one when the problem resurfaces.

**Comment by GernotMaier** [comment]
Now I remember: but one test should never influence another test. Would it be easy to let each test create its own sandbox DB?

**Comment by orelgueta** [comment]
These are the same tests in different instances influencing each other though, not different tests.

I need to test whether the current "general" user can create a DB and drop it afterwards. If it can then we can create a temporary DB per test with a random name. It would be wasteful in terms of resources, but it probably isn't a big deal.

**Comment by GernotMaier** [comment]
OK - each unit test should work in each own sandbox and running them in parallel with different python versions (or simulation software versions) should not break the tests. But if it takes a lot of resources, then better to not do it and find another solution.
