### ISSUE TITLE
Review definitions and usage of Exceptions for setting workflow

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#235]
Review error messages and exceptions for setting workflows.

**Comment by GernotMaier** [comment]
@orelgueta  - I've looked through all exceptions for the setting workflow (including validate_data and validate_schema) and I am not sure if we need to come up with some specific exceptions in these cases. Seems to be ok with using the standard ones.

**Comment by orelgueta** [comment]
OK, no problem. In most cases I didn't define my own either.
