### ISSUE TITLE
Start using new argparser

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#248]
Modify the argparse everywhere to use the new implementation of our own argparser in #247.

**Comment by GernotMaier** [comment]
`applications/add_file_to_db.py` is not working without a `config.yml` file in the gammasimtools directory, as `db = db_handler.DatabaseHandler()` is called before the CommandLineParser (and db_handler.py tries to read the configuration).

Simply remark this here - we will have to discuss what to do with the configuration.

**Comment by GernotMaier** [comment]
argparse has been modified for all applications in the CI-unittest branch (issue will close with merge request)
