### ISSUE TITLE
Hardcoded gaps to determine neighbour pixels

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#25]
Just want to be sure that we are happy with hardwiring the gaps:

https://github.com/gammasim/gammasim-tools/blob/e5105c0b31b8365647252c44642a7783ac203cb5/simtools/model/camera.py#L378

**Comment by orelgueta** [comment]
This was tested to work for all camera types including CHEC-M. Since we don't expect major camera changes, especially not ones with larger gaps, I would say this is fine.
There's no reason to put these values as user input of course. Making them into constants could work, but it is not really necessary considering they are used only here and are not expected to change.

**Comment by GernotMaier** [comment]
I actually expect major changes, if not now, then in 3-6 years.

**Comment by RaulRPrado** [comment]
I'd make it a constant by now for the sake of readability, at least.

**Comment by orelgueta** [comment]
> I actually expect major changes, if not now, then in 3-6 years.

You expect the cameras to change majorly in the next 3-6 years in a way that would introduce larger gaps between pixels??

Either way, I will make those into constants. @RaulRPrado, should I put the constants in the util or here in the camera class?

**Comment by RaulRPrado** [comment]
If it's the same value for all the cameras, I'd define it in the init, using all capital name. If you need a dictionary, I'd use the model_parameters module.

**Comment by orelgueta** [comment]
It's the different for SiPM and PMT cameras, so only two options. Therefore, probably the init is better.

**Comment by RaulRPrado** [comment]
Ok.
There is actually the option of defining it before the init, as a class variable. I do this sometimes.
It doesn't make much difference though.

**Comment by orelgueta** [comment]
With a self or without? Cause in the init it probably has to be with a self.

**Comment by GernotMaier** [comment]
Just think about the discussion on the larger FOV - so I wouldn't be surprised about any changes.

**Comment by RaulRPrado** [comment]
With a self.
It really has no impact technically. It's only an organizational thing.

**Comment by orelgueta** [comment]
OK, added them below the class without a self (Google suggests that is better) and refer to them with a self later.
