### ISSUE TITLE
Separation of unit and functional / integration test

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#256]
Running all unit tests through takes quite some time (10-15 min). This is related to the issue that we mix functional/integration and unit tests. Have discussed this with Raul before, that those should be separated.

- [test_applications.py](https://github.com/gammasim/gammasim-tools/blob/master/applications/tests/test_applications.py) are functional tests only, and take also longest (see table below)
- suggest to have a separate workflow for functional tests
   - implication might be that the unit test part will not need a corsika/sim_telarray installation
   - might affect our coverage (which is ok, as it might be now overestimated as we include functional tests
- need to have a thorough look into the functional tests - at this point some of them test that the application runs without error, but does not test the results of running the application.

Ranking of ten longest tests:
```
============================= slowest 10 durations =============================
329.59s call     applications/tests/test_applications.py::test_applications[tune_psf]
54.80s call     applications/tests/test_applications.py::test_applications[validate_camera_fov]
46.57s call     simtools/simtel/tests/test_simtel_histograms.py::test_histograms
30.66s call     applications/tests/test_applications.py::test_applications[produce_array_config]
27.47s call     applications/tests/test_applications.py::test_applications[validate_optics]
27.36s call     simtools/model/tests/test_array_model.py::test_exporting_config_files
22.45s call     simtools/tests/test_ray_tracing.py::test_rx
22.35s call     applications/tests/test_applications.py::test_applications[compare_cumulative_psf]
17.93s call     simtools/tests/test_ray_tracing.py::test_single_mirror
15.80s call     applications/tests/test_applications.py::test_applications[validate_camera_efficiency]
============ 120 passed, 6 skipped, 4 warnings in 831.79s (0:13:51) ============
```

Review the top ones (`test_applications.py::test_applications[tune_psf]` takes 5-6 min alone) and try to improve the tests.

**Comment by orelgueta** [comment]
Note that I changed the number of photons in the ray tracing a few weeks ago. I increased it in order to have better statistics and that may affect some of the tests, in particular the tune_psf one. There's a chance that fixing #241 and #259 will reduce the duration of the tests significantly. Doesn't mean this issue should not be addressed, just something to keep in mind with respect to its urgency.
