### ISSUE TITLE
Discussion of parameters in config.yml

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#279]
Agreed that the `config.yml` file is probably not needed in future with the extensive usage of the database. Discuss here the meaning of the individual parameters and how to replace them.

Parameter currently set in config.yml:

- DB-related parameters (useMongoDB, mongoDBConfigFile): use hardwired values (what about passwords?) and/or environmental variables
- `modelFilesLocations`: not need anymore as we expect always a connection to the database (would that work already now? see below where it is called)
- `outputLocation`: replace by default value or overwritten by command line parameter
- `testDataLocation`: should be replaced by hardwired value to `tests/resources`, best through a function defined in `tests/conftest.py`
- `dataLocation`: used to get 
	- schema files in `data/parameters` (camera-efficiency_parameters.yml, array-simulator_parameters.yml, ray-tracing_parameters.yml, layout-array_parameters.yml, telescope-position_parameters.yml, simtel-runner-array_parameters.yml) 
	- layout files from data/layout/ used for e.g. for trigger sims: --> move to DB?
	- default CORSIKA parameters: `./data/corsika/corsika_parameters.yml`
	- default simtel_array parameters: `data/parameters/simtel-runner-ray-tracing_parameters.yml` 
- `simtelPath`: use environmental variable
- `submissionCommand`: used for production.py and sim_showers_for_trigger_rates.py : use command line or environmental variable? This is specific to the setup and we need to revisit it (current setup work (as far as I can see) with qsub; we move at DESY to HCcondor; this should be a flexible setup)
- `extraCommands` : related to job submission and currently only used to set environmental variables correctly for running sim_telarray (ZSTD). Might add this similar as `simtelPath` as required environmental variable?

Issue #59 is related to this discussion.

@orelgueta - let me know your opinion, I would then prepare a list of tasks.

#### modelFilesLocations

```
find . -name "*.py" -exec grep -H modelFilesLocations {} \;
./simtools/config.py:        allLocations = get(par="modelFilesLocations")
./simtools/config.py:        "modelFilesLocations": ".",
./simtools/tests/test_config.py:            "modelFilesLocations",
./simtools/tests/test_config.py:        print("modelFilesLocations: {}".format(cfg.get("modelFilesLocations")))
./simtools/model/array_model.py:        modelFilesLocations=None,
./simtools/model/array_model.py:        self._modelFilesLocations = cfg.getConfigArg(
./simtools/model/array_model.py:            "modelFilesLocations", modelFilesLocations
./simtools/model/array_model.py:                    modelFilesLocations=self._modelFilesLocations,
./simtools/model/telescope_model.py:        modelFilesLocations=None,
./simtools/model/telescope_model.py:        self._modelFilesLocations = cfg.getConfigArg(
./simtools/model/telescope_model.py:            "modelFilesLocations", modelFilesLocations
./simtools/model/telescope_model.py:        modelFilesLocations=None,
./simtools/model/telescope_model.py:            modelFilesLocations=modelFilesLocations,
./simtools/model/telescope_model.py:            mirrorListFile = cfg.findFile(mirrorListFileName, self._modelFilesLocations)
./simtools/model/telescope_model.py:                "Using the one found in the modelFilesLocations"
./simtools/model/telescope_model.py:                "Using the one found in the modelFilesLocations"
./simtools/model/telescope_model.py:                cameraConfigFile, self._modelFilesLocations
./simtools/db_handler.py:            file = cfg.findFile(fileName, cfg.get("modelFilesLocations"))
./simtools/db_handler.py:        _yamlFile = cfg.findFile(_fileNameDB, cfg.get("modelFilesLocations"))
./simtools/db_handler.py:        yamlFile = cfg.findFile("parValues-Sites.yml", cfg.get("modelFilesLocations"))
```

**Comment by orelgueta** [comment]
Yes I agree with everything and we actually took care of quite a lot already in #266. 

The DB password might still have to be given in a config file, unless I manage to find a smart solution.

**Comment by GernotMaier** [comment]
One additional thought and to avoid ending up in a inconsistent state of configuration parameters given through the command line, through environmental variables, through default values, etc. Why aren't we more flexible and allow all?

- any configuration parameter can be set through the command line parser
- complex and long configurations can be given through a configuration file (in e.g., yaml format)
- a subset of configuration values can also be given by environmental variables (probably no need to do this for all)
- for easy repeatability - we can write the configuration parameters into a file when running an application and reuse it later.

There are packages providing this, e.g. https://github.com/bw2/ConfigArgParse
On our level, it seems almost easier to add a file reader / writer to commandline_parser module and let this one also the environmental parameters.

**Comment by orelgueta** [comment]
Yes, this is a good idea. I think the original intention was to at least not enforce the use of a config file. Making it optional is best indeed.

I don't think we should add a package for this. The functionality we need is quite basic and can be done with the `commandline_parser`.

Saving the configuration into a file that can be used later is a very nice idea and probably necessary for provenance anyway.

**Comment by GernotMaier** [comment]
A bit confused about the configuration discussion and I really don’t want to get this out of hand and a too big endeavour.

Main goal is to simplify the handling of config.yml and best avoid it. I've scanned again through the code and this is my suggestion:

1. set simtelPath
—> suggest to require always environmental variable
2. get outputLocation
--> use default `./`, otherwise set via command line
3. get dataLocation
--> use default `./data`, otherwise set via command line
4. get modelFilesLocations
--> what to do? Still needed?
5. get submissionCommand and get extraCommands
--> this is very specific to ./simtools/simulator.py and runners: suggest to have it as a command line argument 
7. finding a file: e.g. `cfg.findFile(mirrorListFileName, self._configFileDirectory)`
--> function could be part of io_handler
8. get `useMongoDB` --> not needed anymore, as always True (?)
9. `mongoDBConfigFile`: not sure what the idea is here?
--> suggest to default to dbDetails.yml and otherwise add a command line argument?

Open questions are:
1. Where to read environmental variables?
- could be a simple addition to CommandLineParser
- or add a new Configuration class, which is super to CommandLineParser
2. reading and writing of configuration values
- argparse allows to read command line argument from file (one argument per line, see https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.convert_arg_line_to_args)
- writing of configuration could be done in a similar way as addition to the CommandLineParser
3. Access of parameters in the code: change CommandLineParser (or if required, a Configuration class) to be a Singelton and callable. 

So main question is if we want to add the functionality of getting variables from the environment and writing the command line arguments to a file to the CommandLineParser or add a new class for that. I don't have a strong opinion.

My feeling is that this solution would be not too big and disruptive.

**Comment by GernotMaier** [comment]
Additional note on submissionCommand and get extraCommands: this probably can go into a the production configuration files, which we anyway require at this point (e.g., https://github.com/gammasim/gammasim-tools/blob/master/tests/resources/prodConfigTest.yml). There is already a dataDirectory field for the corsika/sim_telarray out, which is specific to the computing site.

**Comment by orelgueta** [comment]
> 1. set simtelPath
>    —> suggest to require always environmental variable

Please allow also command-line input

> 2. get outputLocation
>    --> use default `./`, otherwise set via command line

Good. BTW, if these are arguments from the user on the command line, I suggest to switch to snake case everywhere (not in the code, just in the argument).

> 3. get dataLocation
>    --> use default `./data`, otherwise set via command line

Can we change the name to inputData/input_data? Also the directory name? This is what is used now in io_handler (would require a change only there.

> 4. get modelFilesLocations
>    --> what to do? Still needed?

I want to get rid of this. I suggest that either you do not touch it for now and I deal with it after the PR or that we work together in the same branch and I remove it while you deal with the other config points discussed here.

> 5. get submissionCommand and get extraCommands
>    --> this is very specific to ./simtools/simulator.py and runners: suggest to have it as a command line argument

Sounds good.

> 6. finding a file: e.g. `cfg.findFile(mirrorListFileName, self._configFileDirectory)`
>    --> function could be part of io_handler

Sort of related to the modelFilesLocations point above. Suggest to check if can be removed completely. If not, move to io_handler.

> 7. get `useMongoDB` --> not needed anymore, as always True (?)

Correct, not needed anymore.


> 8. `mongoDBConfigFile`: not sure what the idea is here?
>    --> suggest to default to dbDetails.yml and otherwise add a command line argument?

Yes, though I also want to get rid of this file, but I am not yet sure we can, so let's go with your suggestion.


> 
> Open questions are:
> 
> 1. Where to read environmental variables?

In the config module/class I think, when you define it and transfer the args to it.


> * could be a simple addition to CommandLineParser

I don't think it should be in the command line parser, the parser should do only that, parsing the command line.

> * or add a new Configuration class, which is super to CommandLineParser

Yes, that could work. The only problem is accessing the configuration class instance we discussed earlier this week, but it shouldn't be too complicated.

> 
> 2. reading and writing of configuration values
> 
> * argparse allows to read command line argument from file (one argument per line, see https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.convert_arg_line_to_args)
> * writing of configuration could be done in a similar way as addition to the CommandLineParser

Again, I am not sure we should expand CommandLineParser to deal also with files. Especially since I think we will use yaml for configuration rather than an argument per line system. I would pass the file name to the configuration module and read it there.

> 
> 3. Access of parameters in the code: change CommandLineParser (or if required, a Configuration class) to be a Singelton and callable.
> 
> So main question is if we want to add the functionality of getting variables from the environment and writing the command line arguments to a file to the CommandLineParser or add a new class for that. I don't have a strong opinion.

I guess my opinion is to have two separate classes for this. Not a strong opinion, so if you find a reason to keep it all in one class (with a different name, not CommandLineParser), then I don't mind of course.

> 
> My feeling is that this solution would be not too big and disruptive.
