### ISSUE TITLE
Delete branch trigger-rate-simulations

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#281]
Suggest to delete this branch, as it seems to be a start of something - without going very far.

Compare this branch with master: https://github.com/gammasim/gammasim-tools/compare/trigger-rate-simulations

Both trigger_rate.py and test-trigger-rate.py are a copy of the ray-tracing code, probably to be used for something new as template.

I will delete it, ok @orelgueta  ?

**Comment by orelgueta** [comment]
Yes, I deleted it.
