### ISSUE TITLE
Rename and document getConfigPar

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#31]
Comment by @orelgueta: 
OK, looks useful, but I would then suggest to expand a bit the doc to explain it and also change the name. This is not really "collecting", it is still "getting", so I would call it "getConfigPar" instead (also par instead of arg cause it's not an input argument).

**Comment by orelgueta** [comment]
Technically this was done in 876ae23c504f7e103f520d5dcf82948c300fb2b8. Did not expand the documentation though. Should we close this?

**Comment by RaulRPrado** [comment]
Yes, looks fine now.
