### ISSUE TITLE
Adding a pre-commit hook

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#312]
As discussed we should look into adding a pre-commit hook to catch and correct style issues at the commit stage.

A good discussion of pre-commit hooks can be found [here](https://towardsdatascience.com/pre-commit-hooks-you-must-know-ff247f5feb7e), the corresponding file for ctapipe is [here](https://github.com/cta-observatory/ctapipe/blob/master/.pre-commit-config.yaml).

If we follow the ctapipe example, this will change initially quite a bit of code (which is not bad):
- isort will sort the import alphabetically (which is good style)
- black with `--line-length=100` will modify 76 files
- flake8 or pyflakes? We are using in the CI pyflakes. Running flake8 founds a few (easy to fix) additional issues.

Suggest to add additionally the `trailing-whitespace` pre-hook.

For testing this, I am using the [pre-commit](https://pre-commit.com/) tool, which allows to test the changes locally.

Setup:
```
conda install -c conda-forge pre-commit
```
Note that when running it on the DESY wgs, you need to set PRE_COMMIT_HOME to some afs disk, otherwise your home disk will fill up.

Install the applications - run the following in the main gammasim-tools directory:
```
pre-commit install
```

For running it locally (especially to avoid conflicts when merging), do:
```
pre-commit run --all-files
```

Issues can then be seen as in this screenshot - it allows only to commit after fixing the flake8 issues:
<img width="829" alt="Screenshot 2022-08-24 at 15 57 55" src="https://user-images.githubusercontent.com/14001688/186437496-63df9b11-46c3-4d9f-9374-2dd08ab753ed.png">

In rare cases one might want to skip the pre-commit checks. Then do:
```
git commit --no-verify
```

**Comment by orelgueta** [comment]
OK unfortunately (for me) I first looked at the PR, did a little research and found everything that is written in this issue, and only then looked at the issue. 

Everything in #311 looks good to me. Adding `trailing-whitespace` would be good as well I agree.

**Comment by GernotMaier** [comment]
OK - good - then we do with the pre-commit hook. 

I will solve then all the problems outlined on codacy and then ask for a review.
