### ISSUE TITLE
Simplification of io_handler

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#321]
Suggest to simplify io_handler and replacing the explicit functions by more generic ones. `io_handler` is otherwise getting difficult to handle with future additions of types of output and files.

e.g. `getDirectory( datatype, mode )`

with
- mode = ‘corsika, model, etc
- datatype = ‘output, test’, etc

Same to get applied for getFile.

This should reduce significantly the number of lines in io_handler.

**Comment by orelgueta** [comment]
Agree! I will self assign and work on it soon.
