### ISSUE TITLE
Revision of documentation

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#345]
The documentation requires a good read and some updates.

- check for missing application and module documentation
- check for consistent interface description of modules
- add add hints regarding the installation of CORSIKA/sim_telarray (issue #172)

**Comment by VictorBarbosaMartins** [comment]
I am on it.
Question: I dont find the files `set_quantum_efficiency_from_external.yml`, `qe_R12992-100-05b.data.ecsv` and `qe_R12992-100-05b.usermeta.yml` from the example below. Are they in the DB or is there a valid example to point to?
https://github.com/gammasim/gammasim-tools/blob/aa301878b393687ce0da6fa6322e7c75fc94507e/applications/submit_data_from_external.py#L31-L34

**Comment by VictorBarbosaMartins** [comment]
The file used here is also not found. Where could I find an example file to put here?

https://github.com/gammasim/gammasim-tools/blob/aa301878b393687ce0da6fa6322e7c75fc94507e/applications/tune_psf.py#L64-L65

**Comment by GernotMaier** [comment]
Those files are all in the [gitlab](https://gitlab.cta-observatory.org/cta-computing/dpps/simulationpipeline/prototypes/notes/simulation-project-metadata-and-formats/-/tree/main/examples) repo. Not sure if we want to include some examples in gammasim-tools (they are external to it). But we should at least have a comment in the documentation.

**Comment by VictorBarbosaMartins** [comment]
I believe the examples (with files) are important, at least for the user to get a feeling on the file format. In this case, would it be better to refer to the gitlab repo in the documentation or to copy the example files over?

**Comment by VictorBarbosaMartins** [comment]
another option would be to store them in the DB?

**Comment by orelgueta** [comment]
> The file used here is also not found. Where could I find an example file to put here?
> 
> https://github.com/gammasim/gammasim-tools/blob/aa301878b393687ce0da6fa6322e7c75fc94507e/applications/tune_psf.py#L64-L65

This file (and a few others) is in the DB. We have a special DB for test data file like this one. I don't think we should also copy them to GitHub. I think it would be best to add a link to the GitLab for some of the files and for the others to point to the DB, perhaps pointing to an application for getting these test data files (which does not exist, but we can easily write it if you think it makes sense).

**Comment by GernotMaier** [comment]
We may also point towards the integration tests, which is getting the test file from the DB and runs the example as:
```
python applications/submit_data_from_external.py --workflow_config_file tests/resources/set_MST_mirror_2f_measurements_from_external.config.yml --input_meta_file /tmp/pytest-of-root/pytest-1/test-data3/output/test-output/d-2022-10-05/model/MLTdata-preproduction.usermeta.yml --input_data_file /tmp/pytest-of-root/pytest-1/test-data3/output/test-output/d-2022-10-05/model/MLTdata-preproduction.ecsv  --test --configFile /tmp/pytest-of-root/pytest-1/test-data3/config-simtools-test.yml
```
(obviously my tmp setup for pytests)
