### ISSUE TITLE
Create applications/retrieve_file_from_db.py 

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/gammasim-tools#353]
By updating the documentation of the applications (Issue #169 ), we realized that some input files were missing in the directories of gamma-simm tools. After discussions in #169, we decide that we can get the missing files from the DB as it is done in the integration tests.

**Comment by orelgueta** [comment]
I wouldn't alter the application but I would add a different one. From the description I am not sure what functionality you wish to have, is it an application which takes a file name, retrieves from the DB and writes it to some local directory?

**Comment by VictorBarbosaMartins** [comment]
Yes, that is the idea. I would change the name to something like DB_file_IO.py and set up a flag to indicate if it is adding or retrieving a file from the DB. I believe most of the code would be the same, hence, I proposed to unify the two functionalities in one application as we did for the simtelarray/corsika production. If you prefer I could, instead of it, create another application for that. Do you think that another application would be simpler to use?

**Comment by orelgueta** [comment]
I would prefer to keep those two applications separate. Reading a file from a DB is a common activity that anyone can do. Writing a file to the DB should be used less and only by users with the correct permissions. I know it would lead to duplication of code and it would not make it simpler to use, but I think it's better this way regardless.

**Comment by VictorBarbosaMartins** [comment]
Ok, then I will create another application for that. Thanks for your comments!
