### ISSUE TITLE
Catch testeff execution error 

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#37]
In camera_efficiency, catch simtel error and print the relevant piece of its log file.

**Comment by GernotMaier** [comment]
@orelgueta - any ideas what is meant here? 

This is the line where sim_telarray is called: https://github.com/gammasim/gammasim-tools/blob/da7c5ad09b246c511868b5996736892bf62559ac/simtools/camera_efficiency.py#L266

Does Raul wants to catch execution errors (meaning os.system not returning 0) or scan the log file and look for errors?

**Comment by orelgueta** [comment]
I think what he means is to do something like in 

https://github.com/gammasim/gammasim-tools/blob/da7c5ad09b246c511868b5996736892bf62559ac/simtools/simtel/simtel_runner.py#L190-L208

If we don't do it now for camera_efficiency I agree it would be useful.

**Comment by GernotMaier** [comment]
OK. After looking also into the subprocess issue, my suggestion is to try and use for all simtel calls the simtel_runner and have a single place to take care of the system calls, log and error file treatment.

This will simplify as well the introduction of e.g. running sim_telarray in a container (meaning gammasim-tools outside, sim_telarray inside the container).

**Comment by orelgueta** [comment]
Agree, will assign myself
