### ISSUE TITLE
Add option to provide DB details config file

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#377]
At the moment the only way to pass the DB connection details is either explicitly providing in the command line the various parameters or providing a config file which sets up all of the options of gammasim-tools, including the dbDetails.yml file. There's also the option to use ENV variables, but that's not relevant for this issue. It would be good to have the option to also provide something like `--db_config_file` that sets up just the DB connection details.

Also, in a quick test @VictorBarbosaMartins performed, the normal `--config` option didn't work, so we should take this opportunity to test and fix that as well.

**Comment by GernotMaier** [comment]
To separate the points discussed above:

1. You  want to have something like:
```
--dbconfig dbconfig.yml
```
as a flag? That should be trivial to add.

2. ``-config``: I've just tested it and it works:
```
db_api_user:
  api
db_api_pw:
  THEPASSWORD
db_api_port:
  THEPORT
db_server:
  THESERVER
```

and then 

```
python applications/get_file_from_db.py --config config.yml --file_name mirror_CTA-S-LST_v2020-04-07.dat
```

@VictorBarbosaMartins - could you give me an example which is not working for debugging?

3. Environmental variables: this is actually not so different to a config file and can be done by having a script to be sources which exports the relevant values. I am starting a gammasim-tools session with `source ./set_DB_environ.sh`

So should I go ahead and add the `--dbconfig`` flag?

**Comment by orelgueta** [comment]
> To separate the points discussed above:
> 
> 1. You  want to have something like:
> 
> ```
> --dbconfig dbconfig.yml
> ```
> 
> as a flag? That should be trivial to add.

Yes, that's exactly what I wish to have (but the argument should be rather `--db_config`).


> 2. `-config`: I've just tested it and it works:
> 
> ```
> db_api_user:
>   api
> db_api_pw:
>   THEPASSWORD
> db_api_port:
>   THEPORT
> db_server:
>   THESERVER
> ```

Should these definitions be in `config.yml` directly? In that case, this is the issue. We thought we still have to point to a `db_details.yml` file in `config.yml`. If these definitions go directly into `config.yml`, that is better and we should keep it like that.


> 3. Environmental variables: this is actually not so different to a config file and can be done by having a script to be sources which exports the relevant values. I am starting a gammasim-tools session with `source ./set_DB_environ.sh`

Yes, that's also what I do (and now @VictorBarbosaMartins does as well).

> So should I go ahead and add the `--dbconfig`` flag?

Yes please!

**Comment by VictorBarbosaMartins** [comment]
My test probably didnt work because I havent passed the DB information in the config.yml
If the db information can go in the config.yml, we should not need  the db_details.yml at all, no?

**Comment by orelgueta** [comment]
Well, that was essentially my question, whether we can pass the DB info directly in `config.yml`. I would still vote for adding the option of adding a config file which contains just the DB info with `--db_config`.

**Comment by VictorBarbosaMartins** [comment]
I see. I would prefer to merge both config files and pass only one. there will always be a DB in gammasim-tools, so no need to separate it from the main config, unless we want to move away from MongoDB one day

**Comment by orelgueta** [comment]
Yes, you are right, if we can already pass the DB info directly in `config.yml`, then we don't need the additional option of `--db_config`. Can you maybe test it? If that works then we can already close this issue without doing anything.

**Comment by VictorBarbosaMartins** [comment]
- I first unset the environmental variables through:
`unset DB_API_PORT
unset DB_SERVER
unset DB_API_USER
unset DB_API_PW
unset DB_API_AUTHENTICATION_DATABASE`

- I included the db information in the config.yml
`dataLocation: ./data/
extraCommands: []
modelFilesLocations: .
outputLocation: .
simtelPath: .
useMongoDB: true
db_api_port: 27017 # Port on the MongoDB server
db_server: 'cta-simpipe-protodb.zeuthen.desy.de' # MongoDB server
db_api_user: 'api' # username for MongoDB
db_api_pw: PASSWORD HERE # Password for MongoDB
db_api_authentication_database: 'admin'`

- Finally I ran 
`python applications/get_file_from_db.py --file_name MLTdata-preproduction.ecsv --config config.yml`

It did not work. Either I did something wrong above (you can tell me) or passing the DB information through config.yml is not working. Maybe @GernotMaier hasn't unset the environmental variables before passing the config.yml in his test?

**Comment by GernotMaier** [comment]
> - I first unset the environmental variables through:
> ```
> unset DB_API_PORT
> unset DB_SERVER
> unset DB_API_USER
> unset DB_API_PW
> unset DB_API_AUTHENTICATION_DATABASE
> ```
> 
> - I included the db information in the config.yml
> ```
> dataLocation: ./data/
> extraCommands: []
> modelFilesLocations: .
> outputLocation: .
> simtelPath: .
> useMongoDB: true
> db_api_port: 27017 # Port on the MongoDB server
> db_server: 'cta-simpipe-protodb.zeuthen.desy.de' # MongoDB server
> db_api_user: 'api' # username for MongoDB
> db_api_pw: PASSWORD HERE # Password for MongoDB
> db_api_authentication_database: 'admin'
> ```
> 

This is the wrong syntax. Look at my example above, the keys in the config file should be the same as the command line parameters.




> - Finally I ran 
> `python applications/get_file_from_db.py --file_name MLTdata-preproduction.ecsv --config config.yml`
> 
> It did not work. Either I did something wrong above (you can tell me) or passing the DB information through config.yml is not working. Maybe @GernotMaier hasn't unset the environmental variables before passing the config.yml in his test?

**Comment by GernotMaier** [comment]
> Yes, you are right, if we can already pass the DB info directly in `config.yml`, then we don't need the additional option of `--db_config`. Can you maybe test it? If that works then we can already close this issue without doing anything.

I want to emphasize here the approach of the new configuration class: any parameter can be set on the command line, through a config file, or through env variables. The names/keys are always those which appear in the help. Env variables can also be in capital letters. All configuration parameters are treated in the same way - this was one of the main motivation for the large changes.

**Comment by VictorBarbosaMartins** [comment]
Sorry for the mistake. It worked now for me with the following config file:
```
db_api_port: 27017 # Port on the MongoDB server
db_server: 'cta-simpipe-protodb.zeuthen.desy.de' # MongoDB server
db_api_user: 'api' # username for MongoDB
db_api_pw: PASSWORD HERE # Password for MongoDB
db_api_authentication_database: 'admin'
```

**Comment by orelgueta** [comment]
OK so in that case we don't need any changes and can close this issue. If anyone objects, please re-open.
