### ISSUE TITLE
Simplify applications/derive_mirror_rnda.py

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/gammasim-tools#378]
By updating the documentation I came across this issue: we could get rid of the argument--psf_measurement in applications/derive_mirror_rnda.py because, as seen in the unit test, the same file is passed twice: as --miror_list and as --psf_measurement. Why not just use the file only once and adjust the code to read the PSF measurement from the miror_list argument instead?

**Comment by GernotMaier** [comment]
The idea is here that we do not want to require that those data is in the same file (list of mirrors and psf results). I know that it is duplicated right now, but l would prefer to have the logical separation.

**Comment by orelgueta** [comment]
I agree, the flexibility of providing it in separate files or providing just one set of data is worth the duplication.

**Comment by VictorBarbosaMartins** [comment]
ok, then lets keep it that way
