### ISSUE TITLE
Use visualize module for ray tracing plots.

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#39]

**Comment by orelgueta** [comment]
Would you like me to do it or do you want to take the opportunity to learn?
Actually this goes a bit further than just using visualize. I think we should take the opportunity to change from using a dictionary of lists, to astropy tables. It is easier to use, compatible with visualize "out-of-the-box" and the preferred data structure in ctapipe. I can also do that change if you wish.

BTW, these definitions 

https://github.com/gammasim/gammasim-tools/blob/04d5ac6a7b84b2eaf8852da460915aed34882fd8/simtools/ray_tracing.py#L243

can be avoided by calling `_results = defaultdict(list)` once, as in

https://github.com/gammasim/gammasim-tools/blob/04d5ac6a7b84b2eaf8852da460915aed34882fd8/simtools/camera_efficiency.py#L285

(we won't have them anyway if we move to astropy tables, but still useful for future reference.)

**Comment by RaulRPrado** [comment]
You can do it, if you want, no problem. Then I can use it as examples next time.

You can do whatever you want to the plotAndSave function, but please keep the simple plot one.

**Comment by orelgueta** [comment]
OK, I will try to change everything to Astropy tables then.
As usual, can you please send me a couple of ray-tracing files? I have fairly old sst files, not sure if they are still OK.
(I promise to one day fight with the Mac compilers and install sim_telarray locally...)

**Comment by orelgueta** [comment]
Done.
