### ISSUE TITLE
Freshen up the documentation theme

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#392]
This is an absolute critical update - let's try and agree on a more modern theme for the documentation.

Sphinx build in themes can be found here: https://www.sphinx-doc.org/en/master/usage/theming.html#builtin-themes

If you want to try them out, simply change the following line and rerun `make html`:
https://github.com/gammasim/gammasim-tools/blob/a7bd959ce142b2c43bc8017c23def654c9c3e180/docs/source/conf.py#L112

If you don't vote, I will choose!

**Comment by orelgueta** [comment]
You don't like the classic? I think it's the best one to be honest.
If not, I would vote for `bizstyle`

**Comment by GernotMaier** [comment]
It looks like 1980. bizstyle is good in my opinion.

**Comment by VictorBarbosaMartins** [comment]
I also prefer the classic one, very friendly and a common face. No objections if you prefer to change to bizstyle

**Comment by GernotMaier** [comment]
OK - it seems there is kind of a majority for classic. So let's ugliness rule and we leave it for now.
