### ISSUE TITLE
Module organisation

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#395]
I want to look into our API documentation, but we first have to decide if we want to change the module organisation. 

We've added quite a few modules / changed code and I think we should re-think how we organize them (minor modification only).

These are my suggestions for changes:

- new `configuration` directory including configuration.py, commandline_parser.py
- new 'data_model' directory including data_model.py, model_data_writer.py, validate_data.py, validate_schema.py, workflow_description.py
- `job_submission` - suggest to rename it to `job_execution` or `execution`. There is only one module in this directory, but I would like to add one more (which separates calling any external software from the rest of the code and allows for easier integration of containers)
- `util/model.py` is a bit confusing, as there is also a model directory. I suggest to rename it and move it to model/model_utils.py

**Comment by orelgueta** [comment]
No objections!

**Comment by VictorBarbosaMartins** [comment]
Uh, that sounds like another big change. maybe we should get the code review first before changing the structure of the code? We will anyways receive a lot of suggestions in this regard

**Comment by GernotMaier** [comment]
No, that won't be a big change. And I don't want to write now documentation for something we anyway change in a couple of months.

This involves the following steps:
- `git mv` of the files
- change of the corresponding import statements

Don't think this is a lot.

**Comment by VictorBarbosaMartins** [comment]
> No, that won't be a big change. And I don't want to write now documentation for something we anyway change in a couple of months.
> 
> This involves the following steps:
> 
> * `git mv` of the files
> * change of the corresponding import statements
> 
> Don't think this is a lot.

In that case that sounds good. We should just remember ourselves to also update the documentation right after the change
