### ISSUE TITLE
Review input to applications/compare_cumulative_psf.py

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#400]
`applications/compare_cumulative_psf.py` reads in the MC model parameters defining the PSF (mirror_reflection_random_angle,  mirror_align_random_horizontal, mirror_align_random_vertical) from a file, although they could/should be directly accessible from the DB. 

For completeness, this is read in by `applications/compare_cumulative_psf.py`:
```
mirror_reflection_random_angle: '0.0075,0.15,0.035'
mirror_align_random_horizontal: '0.0040,28.,0.0,0.0'
mirror_align_random_vertical: '0.0040,28.,0.0,0.0'
```

**Comment by orelgueta** [comment]
Oh and of course the user can not provide the file with the new parameters and then the values from the DB will be ones used.

**Comment by GernotMaier** [comment]
But the usual workflow is then not to read then from the DB but that the user writes the input file? This is only for testing that we get it from the DB?

(we also need to work on the data formats of all those input files)

**Comment by GernotMaier** [comment]
OK, let's leave it and close this one.
