### ISSUE TITLE
Add a function to copy a telescope configuration in the DB

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#41]
The idea is that once a new telescope is defined, we can easily create an entry for it in the DB. In this context, "a new telescope defined" refers to a telescope that moves from design configuration to "real life" configuration. For example, once the first MST is constructed on site, it will have its exact mirror list/configuration which will differ from the design.

@RaulRPrado, do you think we should copy also the full history of the design into the new telescope? 
My current opinion is yes, because if we want to produce MC with an old configuration, it would work "out-of-the-box" this way. However, it creates duplication in the DB that perhaps could be solved in the code by picking up old configuration from the design telescopes in case it does not exist for the real telescope.

**Comment by RaulRPrado** [comment]
> @RaulRPrado, do you think we should copy also the full history of the design into the new telescope?
> My current opinion is yes, because if we want to produce MC with an old configuration, it would work "out-of-the-box" this way. However, it creates duplication in the DB that perhaps could be solved in the code by picking up old configuration from the design telescopes in case it does not exist for the real telescope.

Maybe we don't need it. I think it's an extra complication.
An old configuration would mean that the design is repeated for those non-existing telescopes. This info should be stored somewhere, no?

**Comment by orelgueta** [comment]
Potentially it is always stored in the design telescopes, e.g., South-LST-D. We can always read "history" from there I guess.

**Comment by orelgueta** [comment]
Included in #45.
