### ISSUE TITLE
Reordering of modules

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/gammasim-tools#410]
In this issue I propose we discuss another reordering of the modules.
- As discussed before, we would like to create a directory (*visualization*) inside *gammasim-tools/simtools* and move both *visualize.py* and *legend_handlers.py* to it;
- I propose we unify categories: Use the subdirectories in gammasim-tools/simtools as categories and organize *tests/integration_tests/test_applications.py* according to it (and vice-versa!). For example, we can create a repository in *gammasim-tools/simtools* and gather the modules related to *optics* together, as it is already done in  *tests/integration_tests/test_applications.py* in the command line comments;
- I would like to leave no module without a category. By now, *camera_efficiency*, *db_handler*, *io_handler*, *psf_analysis*, *ray_tracing*, *simulator*, *version*, *visualize* are in *gammasim-tools/simtools* but dont belong to any subdirectory.

**Comment by GernotMaier** [comment]
> In this issue I propose we discuss another reordering of the modules.
> 
>     * As discussed before, we would like to create a directory (_visualization_) inside _gammasim-tools/simtools_ and move both _visualize.py_ and _legend_handlers.py_ to it;

OK.

> 
>     * I propose we unify categories: Use the subdirectories in gammasim-tools/simtools as categories and organize _tests/integration_tests/test_applications.py_ according to it (and vice-versa!). For example, we can create a repository in _gammasim-tools/simtools_ and gather the modules related to _optics_ together, as it is already done in  _tests/integration_tests/test_applications.py_ in the command line comments;

Wait - modules and applications are independent of each other. We will have (or have already) applications which use modules from several module directories. Note that `tests/integration_tests/test_ray_tracing.py` is a bit of an outlier in our testing routines and needs to be improved (nothing is tested, there is not a single assert statement in this code).


> 
>     * I would like to leave no module without a category. By now, _camera_efficiency_, _db_handler_, _io_handler_, _psf_analysis_, _ray_tracing_, _simulator_, _version_, _visualize_ are in _gammasim-tools/simtools_ but dont belong to any subdirectory.

Not sure and we follow here pretty much the approach of other CTA projects like ctapipe and gammapy.

- simulator is a generic class used any modules in corsika or simtel; this hierarchy is missing
- version.py defines a basic characteristic and should have a prominent place
- visualize has been discussed and could be moved
- ray_tracing is logically similar to the simulator and should be visibly higher in the hierarchy
- psf_analysis is the outlier and I agree that we might want to put it somewhere (we probably will add later more of this type of moduls). The question is, if we want to do it now and maybe choose a wrong name for the directory (ok, we can change) - or if we simply wait and see what is coming.

**Comment by VictorBarbosaMartins** [comment]
> Wait - modules and applications are independent of each other. We will have (or have already) applications which use modules from several module directories. Note that tests/integration_tests/test_ray_tracing.py is a bit of an outlier in our testing routines and needs to be improved (nothing is tested, there is not a single assert statement in this code).

Yes, I haven't thought about the case where one application use more than one module, so forget what I said in this regard.

> Not sure and we follow here pretty much the approach of other CTA projects like ctapipe and gammapy.

Actually gammapy seems to go pretty much along the lines of my ideia (https://github.com/gammapy/gammapy/tree/main/gammapy) while ctapipe has more files in the main directory (https://github.com/cta-observatory/ctapipe/tree/master/ctapipe). 

but we can keep it as it is for now as we want to finish these maintenance PRs and get the code reviewed.

**Comment by orelgueta** [comment]
I can only agree with what was already said. Let's create a visualise directory and wait with the other changes until there are more modules to group together. I will assign this issue to myself so I can take care of the visualise part.
