### ISSUE TITLE
Remove unused defaults_init option in layout_array?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#415]
The option `defaults_init` in

https://github.com/gammasim/gammasim-tools/blob/8cdb37a97cf9c4fcf37ed0380927c28e4735cb3a/simtools/layout/layout_array.py#L193

is not used. @GernotMaier, can I remove it or should I implement a usage for it?

**Comment by GernotMaier** [comment]
yes, this one can be removed. I think this is a leftover of the earlier implementation.

**Comment by orelgueta** [comment]
OK, done in my pylint branch. The issue will be closed when it is merged.
