### ISSUE TITLE
check if model/camera.py::_rotate_pixels() can use the util.general.rotate function

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/gammasim-tools#438]
As discussed before with @Orel, we want to check if `model/camera.py::_rotate_pixels()` can be adjusted to use `util.general.rotate` function. One only rotation function should be enough for all the necessary rotations in the code.

       The function seems to be generic (it is in `general.py`), but here it is about telescope positions? Why e.g., can't we replace  `model/camera.py::_rotate_pixels()` and have only one rotation function?

_Originally posted by @GernotMaier in https://github.com/gammasim/gammasim-tools/pull/429#discussion_r1048465789_

**Comment by orelgueta** [comment]
This should be possible, the only difference between the rotations is the direction. For the pixels the rotation is clockwise and here anticlockwise. The only question is whether we should add an option in this rotation function for the direction or should I change some code in the pixel rotations to accept also anticlockwise rotation (I think I prefer the former).

**Comment by VictorBarbosaMartins** [comment]
It turned out the rotation is clockwise, I just checked now without reassigning the rotated x and y values to the class attributes as @GernotMaier  suggested in #429, and it became clearer to me. The rotation is clockwise. Therefore, it might be even simpler to implement this issue.
