### ISSUE TITLE
Make db_handler into a class

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#44]
@RaulRPrado, would it be a problem if I change db_handler to be a class? I think I don't have a choice if we want to connect only once to the DB instead of each time we want to read from it.

**Comment by RaulRPrado** [comment]
No problem, in principle. 
But how would that work? I don't want to have to initiate an object every time I need to interact with the db.
It would be good to keep the simple interfaces as they are now. E.g. db.getModelParameters in TelescopeModel.

**Comment by orelgueta** [comment]
I understand the wish to keep it simple, I would be happy to have it as is.
However, the issue is that without a class, I cannot keep the connection to the DB open throughout the running of the application. Since we have to open a tunnel and connect remotely to the DB, the overhead of reading from the DB is not small. 

Currently when you run db.getModelParameters, you read a specific telescope. In that case, I simply open a connection, read a full set of parameters for a specific telescope and a specific version, and then close the connection. 
However, if you want to read two telescopes, you need to call that twice, which means opening and closing the connection twice, that's unnecessary overhead (and can lead to connection problems).
It gets much more complicated when we modify the DB (either to update/add parameters or write results).

It would be much simpler if we start an instance of the DB once at the start of an application, which then opens a connection. That connection is kept open throughout the life of the application and is closed only at the end.
I can try implementing it such that it the interaction with the DB stays simple, but it won't be as simple as it is now.

**Comment by RaulRPrado** [comment]
Yes, I understand the issue.

We can then add an argument to the TelescopeModel to pass the DB instance. We can allow for a default value (None) in which we create an instance inside the TelescopeModel class and close it after using it. This way, if you have a very simple application that reads the DB one or tow times, you don't need to worry about it.

(Our design idea of keeping the interaction with the DB restricted only to the telescope_model module is paying off now. It's simpler to fix this issue like that.)

**Comment by RaulRPrado** [comment]
Are you going to work on this soon? I need to work on the branch for the new names, not sure if there will be some serious conflict. Maybe not.

**Comment by orelgueta** [comment]
> We can then add an argument to the TelescopeModel to pass the DB instance. We can allow for a default value (None) in which we create an instance inside the TelescopeModel class and close it after using it. This way, if you have a very simple application that reads the DB one or tow times, you don't need to worry about it.

Do you mean in case an application calls the TelescopeModel twice? That is, once for LST and one for MST? I wonder actually, if it is necessary to have an instance for every telescope, what will we do when there are 15 real telescopes?
Anyway, passing an instance is indeed what I had in mind. Another option is checking in the db_handler if an instance exists and a connection is open. If it is, simply use it. The latter makes TelescopeModel blind to the DB, but it's a bit less flexible. I will think about it while I am implementing and then decide.

> (Our design idea of keeping the interaction with the DB restricted only to the telescope_model module is paying off now. It's simpler to fix this issue like that.)

True, and I am sure it will happen many more times in the future.

> Are you going to work on this soon? I need to work on the branch for the new names, not sure if there will be some serious conflict. Maybe not.

I hope to work on it this week, yes, but I don't think it will create crazy conflicts with your naming work. I suggest we both work freely (in different branches), and keep an eye out on the commits of the other to see if things are getting complicated.

**Comment by RaulRPrado** [comment]
> > We can then add an argument to the TelescopeModel to pass the DB instance. We can allow for a default value (None) in which we create an instance inside the TelescopeModel class and close it after using it. This way, if you have a very simple application that reads the DB one or tow times, you don't need to worry about it.
> 
> Do you mean in case an application calls the TelescopeModel twice? That is, once for LST and one for MST? I wonder actually, if it is necessary to have an instance for every telescope, what will we do when there are 15 real telescopes?

Yes, in the case you create few instances of TelescopeModel.

> Anyway, passing an instance is indeed what I had in mind. Another option is checking in the db_handler if an instance exists and a connection is open. If it is, simply use it. The latter makes TelescopeModel blind to the DB, but it's a bit less flexible. I will think about it while I am implementing and then decide.

Well, checking in the db_handler for an existing instance means keeping a "global" instance. I'm sure that would work, but we need to be careful with any harm that global objects can cause.
I do use global variables in the config, but it's a simpler case. One of the complications for the db is that we need to close the tunnel in the end, which is trick to do with a global instance. 

> I hope to work on it this week, yes, but I don't think it will create crazy conflicts with your naming work. I suggest we both work freely (in different branches), and keep an eye out on the commits of the other to see if things are getting complicated.

Ok

**Comment by orelgueta** [comment]
> > Do you mean in case an application calls the TelescopeModel twice? That is, once for LST and one for MST? I wonder actually, if it is necessary to have an instance for every telescope, what will we do when there are 15 real telescopes?
> 
> Yes, in the case you create few instances of TelescopeModel.

I am sure in the future we will simply use a loop to create the 19 instances for the north. However, should we think/check whether that introduces non-negligible overhead?

> > Anyway, passing an instance is indeed what I had in mind. Another option is checking in the db_handler if an instance exists and a connection is open. If it is, simply use it. The latter makes TelescopeModel blind to the DB, but it's a bit less flexible. I will think about it while I am implementing and then decide.
> 
> Well, checking in the db_handler for an existing instance means keeping a "global" instance. I'm sure that would work, but we need to be careful with any harm that global objects can cause.
> I do use global variables in the config, but it's a simpler case. One of the complications for the db is that we need to close the tunnel in the end, which is trick to do with a global instance.

No, I don't mean to keep a global instance. I want to keep perhaps a default named instance instead. So that instead of passing an instance, you pass a name. If no name is given, we use the default which may already exist. But this is just an idea, until I implement it and see if it works, I cannot be certain about it.

**Comment by orelgueta** [comment]
Done #58
