### ISSUE TITLE
Parameters dict from db_handler

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#50]
@orelgueta , the function getModelParametersFromMongoDB is returning a dict with all the info for each parameter (Value, File, ...). Is this intentional? If so, the telescope_model has to be adapted because it is expecting only a simple dict with only the value of each parameter.

**Comment by RaulRPrado** [comment]
@orelgueta  another question: the site parameters (altitude etc) are not being returning after reading the DB. Shouldn't they be?

**Comment by RaulRPrado** [comment]
> @orelgueta another question: the site parameters (altitude etc) are not being returning after reading the DB. Shouldn't they be?

I think this was working before because in the TelescopeModel the site parameters were being read from the yml files. I removed this part and it does not work anymore. How should we fix it?

**Comment by orelgueta** [comment]
The short answer to all questions is that the MongoDB interface is definitely not yet ready for production. It was merged to the master only due to a mistake in the Git pushes. For anything which is not pure development, I highly recommend to still use the yaml files.
I am currently modifying it to be a class anyway, so there will be many changes in the next commit.

Now, a bit more details:

> the function getModelParametersFromMongoDB is returning a dict with all the info for each parameter (Value, File, ...). Is this intentional? If so, the telescope_model has to be adapted because it is expecting only a simple dict with only the value of each parameter.

Yes, this is intentional. We can write a function in the db_handler that simplifies that dict so that TelescopeModel will get a simple list of parameter/value, but I think it is better to do it outside of the db_handler. The db_handler should just provide a (semi-intelligent) interface to the DB itself.

The site parameters are not included in the DB yet at all. They are not tied to a specific telescope, so they need their own collection, under "Sites" or "Paranal" or something. Need to think about it a bit.
Perhaps the best option would be to implement a "getSiteParameters" function which is called once from TelescopeModel?

**Comment by RaulRPrado** [comment]
> The short answer to all questions is that the MongoDB interface is definitely not yet ready for production. It was merged to the master only due to a mistake in the Git pushes. For anything which is not pure development, I highly recommend to still use the yaml files.
> I am currently modifying it to be a class anyway, so there will be many changes in the next commit.
>

I understand, but at this point we should try to make it work somehow. I changed a lot many module to adapt for the new name scheme that only makes sense because of the DB.

> Now, a bit more details:
> 
> > the function getModelParametersFromMongoDB is returning a dict with all the info for each parameter (Value, File, ...). Is this intentional? If so, the telescope_model has to be adapted because it is expecting only a simple dict with only the value of each parameter.
> 
> Yes, this is intentional. We can write a function in the db_handler that simplifies that dict so that TelescopeModel will get a simple list of parameter/value, but I think it is better to do it outside of the db_handler. The db_handler should just provide a (semi-intelligent) interface to the DB itself.

I agree. It's not a problem at all, we just need to make it consistent with the dict from the ymal files.

> The site parameters are not included in the DB yet at all. They are not tied to a specific telescope, so they need their own collection, under "Sites" or "Paranal" or something. Need to think about it a bit.
> Perhaps the best option would be to implement a "getSiteParameters" function which is called once from TelescopeModel?

I agree.

By now I'll do an ugly hack on the TelescopeModel to add the site parameters and change the structure of the dict, so I can test my changes before PR-ing it. We should try to fix this soon though.

**Comment by orelgueta** [comment]
Sure, I am working on it now to make it usable. It's at the top of my to-do list.
I would wait a bit with a PR though, let's first also include the change to a class everywhere before you do a PR. It will probably be cleaner.

**Comment by RaulRPrado** [comment]
Well, I'm not sure about it. I did some changes on the db_handler that you might want to see before finishsing with your branch.
I'm almost done with mine, and will do the PR soon. I don't need to merge it soon after that.

**Comment by orelgueta** [comment]
Changes to the db_handler?? That's gonna hurt...
OK, we will see, probably will need some manual merging...

**Comment by RaulRPrado** [comment]
Small stuff only

**Comment by orelgueta** [comment]
OK, so I just committed the new class like db_handler. I will wait for your changes first, include them and then go over the rest of the code to make it compatible with the new class definition. After that we can include the sites parameters in the TelescopeModel and do a final merge.

**Comment by RaulRPrado** [comment]
Ok. I'm basically done with my branch but will do the PR tomorrow because I need to explain few things.

**Comment by orelgueta** [comment]
OK!

**Comment by orelgueta** [comment]
https://github.com/gammasim/gammasim-tools/blob/3a799d105a719bc53e3fb90b5b33c31ee567673f/simtools/model/telescope_model.py#L229-L234

Why should this be done in the db_handler? I am not sure I agree.
The next part about the site I agree (will include that in the next commit).

**Comment by RaulRPrado** [comment]
In case we decide that db_handler should provide a simple structured dict.
The other option is dealing with the more complicated dict at the telescope_model, which is also fine. I didn't do much thought before writing the warning message.

**Comment by RaulRPrado** [comment]
Can we close this one?

**Comment by orelgueta** [comment]
Why would we close it? First we have to make the decision and implement it, no?
My opinion is that TelescopeModel should receive the dict and use it everywhere (it can modify it if necessary).

**Comment by RaulRPrado** [comment]
That is already implemented, we just need to remove the warning. Can you do that in your DB branch?

**Comment by orelgueta** [comment]
Sure, I can do that. However, I thought the plan is to use the full dict from now on. Currently you are sort of "deleting" valuable information that comes from the DB.
I thought it shouldn't be too much work, since in most places you get a parameter value with getParameter, no?

**Comment by RaulRPrado** [comment]
Yes, right.
It's a bit of work actually. The TelescopeModel has to be changed in several parts.
I would prefer to do that in a separate PR and keep it as it is now.
And we could create another issue for that. This issue was meant for a easy solution to fix some bugs from pytest.

**Comment by orelgueta** [comment]
OK, no problem. Closing this for now then.
