### ISSUE TITLE
Add sites and old SSTs to MongoDB

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#51]
@RaulRPrado, what names did we decide for the sites and old SST entries?

**Comment by RaulRPrado** [comment]
For the soon-coming PR, I used Site-SST-ASTRI, Site-SST-1M, Site-SST-GCT. But we can redefine them if you want.

**Comment by orelgueta** [comment]
Thanks. "Site" in this case will always be "South" right?

What about the name of the sites themselves? How should they be named in the DB?

**Comment by RaulRPrado** [comment]
Yes, South or North.

The sites will be equivalent to a telescope in the DB? Maybe only South and North may be confusing because these are parts of the telescope names. What about something like Site-South and Site-North?

**Comment by orelgueta** [comment]
The sites will not be equivalent to telescopes, so we don't need Site-South. The entry itself will probably be Site: "South", or something like that. 
The question is, when you read the site information, what do you keep internally? If you get a dictionary back that provides and entry such as "Site": "Paranal/LaPalma", would that be OK?

I am actually considering creating a separate DB or separate collection for the sites, what do you think?

**Comment by RaulRPrado** [comment]
Ok, I see.
Well, now that we are using "South" and "North" for the telescope names, we should keep it consistent in the DB.

> The question is, when you read the site information, what do you keep internally? If you get a dictionary back that provides and entry such as "Site": "Paranal/LaPalma", would that be OK?

I think so.

> I am actually considering creating a separate DB or separate collection for the sites, what do you think?

I think that makes sense. When building an array model, we won't repeat the site parameters for each telescope. So makes sense to keep it separetly.

**Comment by orelgueta** [comment]
OK, I will add the site info to the DB soon. We'll see what's the best way to do it (probably a collection).

**Comment by orelgueta** [comment]
The site parameters are included in MongoDB.
Now the question is, @RaulRPrado, how would you like to read them? At the moment it looks like you save only two of them "atmospheric_transmission" and "altitude", and they are saved in the dict in a simple manner, i.e.,

`self._parameters["atmospheric_transmission"] = some value`

without any mention of the site or anything like that.

My original thought was to write a method in the db_handler which returns a full dict with all site parameters for a given site/version. Later, in the telescope model, you can extract from the dict whatever you want. What do you think?

**Comment by RaulRPrado** [comment]
> My original thought was to write a method in the db_handler which returns a full dict with all site parameters for a given site/version. Later, in the telescope model, you can extract from the dict whatever you want. What do you think?

That sounds good. It is a good idea to keep the parameters selection out of the db_handler.

**Comment by orelgueta** [comment]
OK, done this way. Let's see what you think about the PR.

**Comment by orelgueta** [comment]
Done in #58
