### ISSUE TITLE
db_handler must raise an error when parameters are requested for a non-existing telescope name

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#52]
At the moment, the db_handler return an empty dict.

**Comment by orelgueta** [comment]
Oh, sorry, I am currently adding the SSTs to it so it's empty at this specific moment.
Give me 10 minutes for it to finish (unfortunately I don't have a sandbox to do these things in).

**Comment by orelgueta** [comment]
Done, the DB is back online.

**Comment by orelgueta** [comment]
Oh, wait, so you want to add this functionality that will check if the telescope exists? I wonder how necessary it is, considering you validate the names beforehand and we don't expect the DB to be empty.

**Comment by RaulRPrado** [comment]
That is the thing, I can't validate the whole telescope name anymore. The list of telescope will increase a lot and in principle the telescope names can be anything, there is no pattern for the full name. The only way to validate it is by keeping a list of telescope names somewhere. But I don't think that makes sense, since this "list" is a DB information.

Raising an error when the parameter dict is empty is a one-line piece of code and it is a good idea anyway, with or without the name validation.

**Comment by orelgueta** [comment]
OK, no problem. I added a check at the level of the query. That is, if the query returns zero entries, a ValueError is raised. My guess is that somewhere down the line this will cause an issue somehow, but we will see.

**Comment by RaulRPrado** [comment]
Well, at the query level is probably dangerous, indeed.
This could be done at the getModelParameters function, just before returning the dict.

**Comment by orelgueta** [comment]
There's no difference, if the query is empty, you will get an empty dict.
If we decide to return something else in this case, we will change it, but for now it makes sense to catch the issue as early as possible.

**Comment by RaulRPrado** [comment]
Done then? Can we close it?

**Comment by orelgueta** [comment]
I will close it when the PR is accepted.

**Comment by RaulRPrado** [comment]
Don't forget to close this one.

**Comment by orelgueta** [comment]
Done in #58.
