### ISSUE TITLE
Removing the new parameters before exporting the simtel config file

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#53]
We added new parameters to the model (particularly camera features that were found only within the camera config file). These parameters cannot be written to the simtel config file, otherwise it doesn't run.

**Comment by orelgueta** [comment]
I think I did this in #58, but not sure if in the right place. You can check and if it's OK, close it I guess.

**Comment by RaulRPrado** [comment]
I saw it and it is fine by now. I might move it to somewhere else when working on adapting the class for the new dict structure. But I think we can close this one.
