### ISSUE TITLE
Change "findFile" to read from the DB?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#59]
Perhaps it would be good to search the DB for files instead of the various directories (if useMongoDB is True)?
At least that is true for the usual dat files which are already in the DB. The files we received from the instrument teams are not included yet (not sure how to include them to be honest).

**Comment by RaulRPrado** [comment]
This function is meant to find a file in a certain directory and return its full path. You can tell it where to search on.
The telescope_model was already changed to search in the same runPath where the DB writes the files, if that is the case.

Do you mean to search for the file before it was written somewhere? If so, I don't think agree. I don't think that should be done by this function. We should use this function at a next level, whenever the files are written somewhere.

**Comment by RaulRPrado** [comment]
Maybe it is misplaced actually. It may make more sense to move it to some util module instead of config.

**Comment by orelgueta** [comment]
What I meant is that if gammasim needs a file, then instead of going to search for it in the various directories, to simply read it from the DB.
I don't mean to replace this function, this function can then be called after we read the file from the DB and write it to some directory. I guess my suggestion is to change the workflow, not the specific function.

**Comment by RaulRPrado** [comment]
Ah ok.
This could be a method from the db_handler then and we can replace it wherever it fits.
By now we don't have many cases for that. The telescope_model needs to write the files anyway so simtel can read them.

**Comment by RaulRPrado** [comment]
Well, maybe the camera fov app. It doesn't run simtel but it does read the camera config file.

**Comment by orelgueta** [comment]
That method more or less exists already

https://github.com/gammasim/gammasim-tools/blob/a8ef880acd621d995df4cad1dcf6bde50388cc58/simtools/db_handler.py#L644

But I can make it a little friendlier once we make a decision to go for it.
I guess we will have to look at the other directories anyway for now, in particular the "dataFromInstrumentTeams" directory, so it's not urgent.

**Comment by RaulRPrado** [comment]
Yeah, that looks good.

Do we still need to give the dbName even though it's a class now?

**Comment by orelgueta** [comment]
No, that's what I meant with making it friendlier. At the moment this function is only used internally. If we want an external one, I would make it go through all known DBs and won't require the name.

BTW, the names of the DBs are currently hard coded in db_handler. Not sure if we should put them in a config file or not...

**Comment by RaulRPrado** [comment]
> No, that's what I meant with making it friendlier. At the moment this function is only used internally. If we want an external one, I would make it go through all known DBs and won't require the name.

Ok, I see.
 
> BTW, the names of the DBs are currently hard coded in db_handler. Not sure if we should put them in a config file or not...

I don't think we should worry about it now. It's fine like that.

**Comment by orelgueta** [comment]
It still exists, called now `find_file` and it's in `simtools/util/general.py`. However, this issue is not really relevant anymore. We do get most files from the DB now and then use this function to get them. Therefore, I am closing this issue as "done".
