### ISSUE TITLE
Adding docstrings to the current modules

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#6]
Many modules are still lacking docstrings. 
Progress list below:

visualize.py
ray_tracing.py
io_handler.py
db_handler.py
corsika_config.py
simtel_runner.py
psf_analysis.py DONE
corsika_parameters.py
config.py
util/names.py
util/model.py
util/general.py
model/telescope_model.py DONE
model/model_parameters.py
model/array_model.py UNFINISHED

**Comment by RaulRPrado** [comment]
visualize.py
ray_tracing.py
io_handler.py
db_handler.py
corsika_config.py
simtel_runner.py DONE
psf_analysis.py DONE
corsika_parameters.py
config.py
util/names.py
util/model.py
util/general.py
model/telescope_model.py DONE
model/model_parameters.py
model/array_model.py UNFINISHED

**Comment by RaulRPrado** [comment]
visualize.py
ray_tracing.py
db_handler.py
corsika_config.py
corsika_parameters.py
util/names.py
util/model.py
util/general.py
model/model_parameters.py

io_handler.py DONE
simtel_runner.py DONE
psf_analysis.py DONE
config.py DONE
model/telescope_model.py DONE
model/array_model.py UNFINISHED (only skeleton of the module)

**Comment by RaulRPrado** [comment]
visualize.py
ray_tracing.py
db_handler.py
corsika_config.py
corsika_parameters.py
model/model_parameters.py

util/names.py DONE
util/model.py DONE
util/general.py DONE
io_handler.py DONE
simtel_runner.py DONE
psf_analysis.py DONE
config.py DONE
model/telescope_model.py DONE
model/array_model.py UNFINISHED (only skeleton of the module)

**Comment by RaulRPrado** [comment]
Working on the develop branch from now on.

visualize.py
ray_tracing.py

db_handler.py DONE
corsika_config.py DONE
corsika_parameters.py DONE
model/model_parameters.py DONE
util/names.py DONE
util/model.py DONE
util/general.py DONE
io_handler.py DONE
simtel_runner.py DONE
psf_analysis.py DONE
config.py DONE
model/telescope_model.py DONE
model/array_model.py UNFINISHED (only skeleton of the module)

**Comment by RaulRPrado** [comment]
All done, but visualize. @orelgueta could you format the docstrings in visualize to numpy format, please? https://numpydoc.readthedocs.io/en/latest/format.html#id4

I'll do a pull request now, so you can do that in the master later.

**Comment by orelgueta** [comment]
Done in 3bf4a7d. Hopefully I got the structure right.

**Comment by RaulRPrado** [comment]
Thanks!
