### ISSUE TITLE
Not part of CorsikaConfig class?

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#61]
@RaulRPrado, why aren't these three functions part of the CorsikaConfig class?

https://github.com/gammasim/gammasim-tools/blob/2463c4fab00c30ff3c1bad0a03f4182cf71cb233/simtools/corsika_config.py#L37

https://github.com/gammasim/gammasim-tools/blob/2463c4fab00c30ff3c1bad0a03f4182cf71cb233/simtools/corsika_config.py#L61

https://github.com/gammasim/gammasim-tools/blob/2463c4fab00c30ff3c1bad0a03f4182cf71cb233/simtools/corsika_config.py#L76

I wanted to put the logger into the class, but it would be nicer if these are in the class as well, instead of having two loggers in the same namespace.

**Comment by RaulRPrado** [comment]
Well, they don't need to be, actually.
But I see no problem at moving them to the class. Feel free do it.

**Comment by orelgueta** [comment]
Done in #62, once the PR is accepted, will close this.
