### ISSUE TITLE
Add steps required when adding an application

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#676]
Adding a new application requires to modify:

- modify pyproject.toml
- docs/resources/applications.rst

Add this to developer documentation.

**Comment by VictorBarbosaMartins** [comment]
By the way, I would also add the guidelines for including a new dependency. I think there are also two places where we have to add the new package name

**Comment by GernotMaier** [comment]
@VictorBarbosaMartins  - the point on dependencies is already addressed at https://github.com/gammasim/simtools/blob/217097cb91d074ccc5497275432c714f64ce124d/docs/source/developer_guidelines.rst?plain=1#L155
