### ISSUE TITLE
Use names instead of titles in numpy structured arrays

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#7]
https://github.com/gammasim/gammasim-tools/blob/484bbeb6490fa436c1b5a3cf7d5f00740f537ada/applications/compare_cumulative_psf.py#L26

This doesn't actually work, I cannot access those titles, nor can you reference the columns using the titles (at least when using loadtxt). Python doesn't complain because the "title" field is more or less ignored. 
So, I suggest that we use the full axis titles in "names". As I mentioned, it shouldn't be an issue, you are not supposed to "guess" the name anyway and having a full name is even clearer than a variable style name.

**Comment by RaulRPrado** [comment]
Ok, fine for me.

**Comment by orelgueta** [comment]
Fixed by 469983f.
