### ISSUE TITLE
Config template

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#73]
https://github.com/gammasim/gammasim-tools/blob/76c43f1965bddcc9ecd77f2f438861ff34615733/config_template.yml#L6

A few comments regarding the config template (I understand that this is not the final solution):

- do we really need the paths on Orel's machine or can we generalize it?
- unclear in the docu (https://gammasim.github.io/gammasim-tools/framework.html) if all of these files are needed. Do we e.g., need the files located in modelFilesLocations ? If yes, then we should add this to the installation instructions.
- what about using environmental variables for e.g., the simtelPath? This would simplify the settings also for e.g. the Docker file.
- do we want to add an example for ./dbDetails.yml ? I cannot see what should be in this file.

**Comment by orelgueta** [comment]
Will let Raul comment on the other stuff.

> * do we want to add an example for ./dbDetails.yml ? I cannot see what should be in this file.

Not sure, it's a private file with a username and password for the DB. I don't see how an example would be useful. Open to discussion though.

**Comment by GernotMaier** [comment]
Problem is that at this point we don't even know what is expected in the file. So I would prefer an file with empty username/pw field compared to know knowing what is missing.

**Comment by RaulRPrado** [comment]
> https://github.com/gammasim/gammasim-tools/blob/76c43f1965bddcc9ecd77f2f438861ff34615733/config_template.yml#L6
> 
> A few comments regarding the config template (I understand that this is not the final solution):
> 
> * do we really need the paths on Orel's machine or can we generalize it?

We can generalize it, no problem.

> * unclear in the docu (https://gammasim.github.io/gammasim-tools/framework.html) if all of these files are needed. Do we e.g., need the files located in modelFilesLocations ? If yes, then we should add this to the installation instructions.

Right. I'll expand the description and make clear which files area needed for what.

> * what about using environmental variables for e.g., the simtelPath? This would simplify the settings also for e.g. the Docker file.

I don't like environmental variables and I'm trying to live without them. I like even less the idea of having some paths as environmental variables and some given at the config file. 

> * do we want to add an example for ./dbDetails.yml ? I cannot see what should be in this file.

I think just a skeleton, without any private info, is fine.

I will apply all the changes to the develop branch and merge it in the end, after approaching all the issues/comments.

**Comment by RaulRPrado** [comment]
> > * what about using environmental variables for e.g., the simtelPath? This would simplify the settings also for e.g. the Docker file.
> 
> I don't like environmental variables and I'm trying to live without them. I like even less the idea of having some paths as environmental variables and some given at the config file.

There may be a way to catch environmental variables in yml files. I'll have a look at this. If that is possible, I will document it.

**Comment by GernotMaier** [comment]
But isn’t it easier to 1-3 environmental variables then to work with a config.yml file plus a shell script which sets one single environmental variables?

**Comment by RaulRPrado** [comment]
> But isn’t it easier to 1-3 environmental variables then to work with a config.yml file plus a shell script which sets one single environmental variables?

It may be easier to implement but it just make more complicated to use it. The thing is that users sometimes don't know if there are only 1, 3 or 15 environmental variables to be set. It's harder to make everything clear for the user with environmental variables.

With the current design, the user will always know for sure that everything he/she needs to setup is there, in one single file, consistently.  

I found a way to allow for enviromental variables in the config file. You will be able to set

simtelPath=$SIMTELPATH

if that is easier for you.

**Comment by RaulRPrado** [comment]
@GernotMaier , I did all these changes on the develop branch. If you want to have a look, you can checkout develop , go to docs, make html and open it with firefox build/html/index.html. The gh-pages will only be updated when I merge the branch with the master.

I added
- more details to the config part of the docs, specially about the modelFilesLocations (including links to the gitlab).
- a comment on evironmental variables (and implemented it).
- comments to the config_template.yml
- a dbDetails_template.yml file. I just removed the user and password. I don't know if everything else is actually public (@orelgueta ?)

**Comment by GernotMaier** [comment]
Checked everything, this is good (actually easier to compare the develop with the master branch than to look at the html output)

**Comment by GernotMaier** [comment]
This should be added to config.yaml?

I tried 
```
simtelPath: '$SIMTELPATH'
```
But get
```

python applications/derive_mirror_rnda.py --tel_name North-MST-FlashCam-D --mean_d80 1.4 --sig_d80 0.16 --mirror_list mirror_MST_focal_lengths.dat --d80_list mirror_MST_D80.dat --rnda 0.0075
Traceback (most recent call last):
  File "applications/derive_mirror_rnda.py", line 209, in <module>
    tel = TelescopeModel(
  File "/workdir/external/gammasim-tools/simtools/model/telescope_model.py", line 100, in __init__
    self._loadParametersFromDB()
  File "/workdir/external/gammasim-tools/simtools/model/telescope_model.py", line 221, in _loadParametersFromDB
    db = db_handler.DatabaseHandler(self._logger.name)
  File "/workdir/external/gammasim-tools/simtools/db_handler.py", line 78, in __init__
    if cfg.get('useMongoDB'):
  File "/workdir/external/gammasim-tools/simtools/config.py", line 86, in get
    if config[par][0] == '$':
TypeError: 'bool' object is not subscriptable
```

**Comment by RaulRPrado** [comment]
Oh sorry, this was a bug created by the previous change that I fixed on the next commit.  I just pushed itIt shoudl work now

**Comment by GernotMaier** [comment]
Yes, thanks!

This is nice, as I use the docker image and can set SIMTELPATH automatically (as in the docker image, simtel_array is installed always in the same directory)

**Comment by RaulRPrado** [comment]
Let's close it?
