### ISSUE TITLE
ModelFilesLocations not found

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#75]
Trying to run an application and some of the data files are not found, e.g., 

```
python applications/derive_mirror_rnda.py --tel_name North-MST-FlashCam-D --mean_d80 1.4 --sig_d80 0.16 --mirror_list mirror_MST_focal_lengths.dat --d80_list mirror_MST_D80.dat --rnda 0.0075
ERROR::config(l178)::findFile::File mirror_MST_focal_lengths.dat could not be found in None
Traceback (most recent call last):
  File "applications/derive_mirror_rnda.py", line 215, in <module>
    mirrorListFile = cfg.findFile(name=args.mirror_list)
  File "/workdir/external/gammasim-tools/simtools/config.py", line 179, in findFile
    raise FileNotFoundError(msg)
FileNotFoundError: File mirror_MST_focal_lengths.dat could not be found in None
```

My configuration file includes the following settings:

```
# configuration file for simtools

useMongoDB: false
mongoDBConfigFile: ./dbDetails.yml

modelFilesLocations: [
  /workdir/external/simulation-model-description/configReports/,
  /workdir/external/simulation-model-description/datFiles/,
  /workdir/external/
]

outputLocation: .

testDataLocation: './data/'

simtelPath: /workdir/sim_telarray/

# Not used yet
submissionCommand: 'qsub '
```

Any idea why it doesn't find the modelFilesLocations ?

**Comment by RaulRPrado** [comment]
These are data from instrument teams, indeed. I can send only these two files for you to test the application. Should I?

**Comment by GernotMaier** [comment]
OK - found the problem:

- dataFromInstrumentTeams is not on the gitlab (at least I couldn't find it)
- running this from a container: doesn't follow any symlinks in attached directories

Maybe we can think about improving the error messages printed above? Had to look into the code to understand if the file name is wrong or one of the data directories.

**Comment by orelgueta** [comment]
> * dataFromInstrumentTeams is not on the gitlab (at least I couldn't find it)

Yes it is:

https://gitlab.cta-observatory.org/cta-consortium/aswg/simulations/simulation-model/verification/data-from-instrument-teams

**Comment by GernotMaier** [comment]
Couldn't find e.g., mirror_MST_focal_lengths.dat on the gitlab, but it was on the svn. Renamed?
