### ISSUE TITLE
Testing derive_mirror_rnda.py

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#76]
Tested the example on https://gammasim.github.io/gammasim-tools/applications.html#module-derive_mirror_rnda and it worked very nice!

Would it be nice to add to the docu page somewhere the expected results, so that one can cross check that everything went well. I have:

```
Measured D80:
Mean = 1.400 cm, StdDev = 0.160 cm

Simulated D80:
Mean = 1.401 cm, StdDev = 0.200 cm

mirror_random_reflection_angle
Previous value = 0.007500
New value = 0.006378
```
I guess this is fine?

Documentation on https://gammasim.github.io/gammasim-tools/applications.html#module-derive_mirror_rnda mentions a run-time of 90 min. It takes on my MacBook (in a docker container) 5m55s.

The plots shown on the documentation page, are they made with gammasim-tools? If yes, then it would be nice to have a link for an example (I assume that this is a simple plotting of distributions). I actually expected some plots, as the description of e.g., d80_list discussed plots.

Did I miss the description in the documentation of how to find the results? 

I guess these are the files in /workdir/external/gammasim-tools/simtools-files/derive_mirror_rnda/ray-tracing/results/ray-tracing-North-MST-FlashCam-D-d0.0-za20.0_derive_mirror_rnda.cvs ? (ok, I found it now at the end of the output when running the application. *simtools-files* is a slightly surprising directory name for all the output. 

ray-tracing-North-MST-FlashCam-D-d0.0-za20.0_derive_mirror_rnda.cvs shows some *nan* in the eff_flen column, is this expected?

```
Offset d80_cm d80_deg eff_area eff_flen mirror_number
0.0 2.6598867711205294 0.09525017872992896 0.22714416906479998 nan 0
0.0 3.1180957245489864 0.11165857820902712 0.22646285504699998 nan 1
0.0 1.8642169976987006 0.06675735379042816 0.2281513289172 nan 2
...
````

Found the plots! Took me a bit to navigate through the output directory (a find on 'pdf' did the job). As said above, a small hint in the documentation would be helpful.

**Comment by GernotMaier** [comment]
Follow up question to understand how this works when running 

```
python applications/derive_mirror_rnda.py --tel_name North-MST-FlashCam-D --mean_d80 1.4 --sig_d80 0.16 --mirror_list mirror_MST_focal_lengths.dat --d80_list mirror_MST_D80.dat --rnda 0.0075
```

and getting:

![derive_mirror_rnda_North-MST-FlashCam-D](https://user-images.githubusercontent.com/14001688/95250647-aed07100-081a-11eb-9475-9e2d251af6a9.png)

- start with random_reflection_angle = 0.075 --> D_80 is too large
- code choses a smaller value for random_reflection_angle; what is the step size? How does it choose rnda for step 2, 3, ...?

**Comment by RaulRPrado** [comment]
> Would it be nice to add to the docu page somewhere the expected results, so that one can cross check that everything went well. I have:
> 
> ```
> Measured D80:
> Mean = 1.400 cm, StdDev = 0.160 cm
> 
> Simulated D80:
> Mean = 1.401 cm, StdDev = 0.200 cm
> 
> mirror_random_reflection_angle
> Previous value = 0.007500
> New value = 0.006378
> ```
> 
> I guess this is fine?

Sure, I'll do that.
Yes, it's fine.

> Documentation on https://gammasim.github.io/gammasim-tools/applications.html#module-derive_mirror_rnda mentions a run-time of 90 min. It takes on my MacBook (in a docker container) 5m55s.

Was this the test when you gave the mirror list files or not?
I can double check that runtime.

> The plots shown on the documentation page, are they made with gammasim-tools? If yes, then it would be nice to have a link for an example (I assume that this is a simple plotting of distributions). I actually expected some plots, as the description of e.g., d80_list discussed plots.

Yes, the plots are all produced by using gammasim-tools, by running the same examples given in the docs.
I don't get it. What other plot do you expect?

> Did I miss the description in the documentation of how to find the results?
> 
> I guess these are the files in /workdir/external/gammasim-tools/simtools-files/derive_mirror_rnda/ray-tracing/results/ray-tracing-North-MST-FlashCam-D-d0.0-za20.0_derive_mirror_rnda.cvs ? (ok, I found it now at the end of the output when running the application. _simtools-files_ is a slightly surprising directory name for all the output.

I will write at the introduction where to find the results and the plots.
The dir name simtools-files is totally flexible. Do you mean it should be something related to "output"?

> ray-tracing-North-MST-FlashCam-D-d0.0-za20.0_derive_mirror_rnda.cvs shows some _nan_ in the eff_flen column, is this expected?

Yes, it is expected. The eff flen is calculated with a parallax algorithm, using for that the lateral displacement of the image. For 0 deg offset, the displacement is zero, so one cannot compute eff flen.  

> Found the plots! Took me a bit to navigate through the output directory (a find on 'pdf' did the job). As said above, a small hint in the documentation would be helpful.

Yes, I'll improve the docs and the stricture of the output files. The directory application should become application-plots actually, because that is all that goes there.

**Comment by RaulRPrado** [comment]
> * start with random_reflection_angle = 0.075 --> D_80 is too large
> * code choses a smaller value for random_reflection_angle; what is the step size? How does it choose rnda for step 2, 3, ...?

The difference between the simulated and measured D_80 determines the direction that rnda should changes (D80 too large -> smaller rnda, and d80 too small -> larger rnda). The step size is hardcoded as 10 % of the initial value of rnda. It's arbitrary but it doesn't need to be finely optimized.
The code continue iterating until the simulated D80 crosses the measured one. After that, as a last step, a linear interpolation between the two last points are used to reach final value.

This algorithm was only tested for this specific case of MST, but it seems to me very likely that will work fine in general. We can do small improvements later e.g. on the hardcoded step size. However, I don't think we need anything fancier. We have to keep in mind that every point in this plot means the ray tracing simulation (~5e4 photons) of every single mirror in the list.

**Comment by GernotMaier** [comment]
Agree that this approach is good.

Did you discuss / think about what to do with those hard coded values? They are certainly good, but I am pretty sure that there are users who want to change them. Maybe an expert configuration mode?

**Comment by RaulRPrado** [comment]
> Agree that this approach is good.
> 
> Did you discuss / think about what to do with those hard coded values? They are certainly good, but I am pretty sure that there are users who want to change them. Maybe an expert configuration mode?

We could make it a command line argument. It's specific for this application anyway. I'll do that already.

**Comment by GernotMaier** [comment]
> On 8. Oct 2020, at 09:53, RaulRPrado <notifications@github.com> wrote:
> 
> ﻿Documentation on https://gammasim.github.io/gammasim-tools/applications.html#module-derive_mirror_rnda mentions a run-time of 90 min. It takes on my MacBook (in a docker container) 5m55s.
> Was this the test when you gave the mirror list files or not?
> 
> I can double check that runtime.
> 
Exactly how it was on the documentation page using a mirror list with 200 mirrors.
> The plots shown on the documentation page, are they made with gammasim-tools? If yes, then it would be nice to have a link for an example (I assume that this is a simple plotting of distributions). I actually expected some plots, as the description of e.g., d80_list discussed plots.
> 
> Yes, the plots are all produced by using gammasim-tools, by running the same examples given in the docs.
> I don't get it. What other plot do you expect?
> 
Sorry - that paragraph was written before I understood the schema of the output directories and before I found the plots. I simply didn’t expect them in a directory called ‘application’. Forget about this paragraph.

> Did I miss the description in the documentation of how to find the results?
> 
> I guess these are the files in /workdir/external/gammasim-tools/simtools-files/derive_mirror_rnda/ray-tracing/results/ray-tracing-North-MST-FlashCam-D-d0.0-za20.0_derive_mirror_rnda.cvs ? (ok, I found it now at the end of the output when running the application. simtools-files is a slightly surprising directory name for all the output.
> 
> I will write at the introduction where to find the results and the plots.
> The dir name simtools-files is totally flexible. Do you mean it should be something related to "output"?
> 
simtools-files is a bit unclear, as it could be input, configuration, log, even some code in my understanding. It is called *outputLocation* in the config.yaml file, maybe something with output would be good.
> ray-tracing-North-MST-FlashCam-D-d0.0-za20.0_derive_mirror_rnda.cvs shows some nan in the eff_flen column, is this expected?
> 
> Yes, it is expected. The eff flen is calculated with a parallax algorithm, using for that the lateral displacement of the image. For 0 deg offset, the displacement is zero, so one cannot compute eff flen.
> 
But zero and Nan is different. Does this mean the eff len == focal length for offsets of zero? (I should read it up in Steve’s optics note).
> Found the plots! Took me a bit to navigate through the output directory (a find on 'pdf' did the job). As said above, a small hint in the documentation would be helpful.
> 
> Yes, I'll improve the docs and the stricture of the output files. The directory application should become application-plots actually, because that is all that goes there.
> 
Thanks!

**Comment by RaulRPrado** [comment]
> But zero and Nan is different. Does this mean the eff len == focal length for offsets of zero? (I should read it up in Steve’s optics note).

This only means that the eff flen cannot be calculated with simulations at 0 deg offset. At least  not using the parallax algorithm.
The nan comes from a 0./0., or something like it. 

That is not a problem. The eff flen that we quote and use is an average over the field of view. The plot is just meant for a quick vizualization.

More:
- output directory name changed to simtools-output
- I still get 90 min runtime. I'll have a deeper look later.

**Comment by GernotMaier** [comment]
I am running it on my new MacBook pro with a 2.3 GHz-Quad-Core i7. Do you run it on the WGS or on your laptop?

**Comment by RaulRPrado** [comment]
Can we close this one? 
I'll create another issue for updating all the runtimes.

**Comment by GernotMaier** [comment]
Yes, can be closed.
