### ISSUE TITLE
Testing validate_optics.py

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#78]
Running the example with
```
python applications/validate_optics.py --tel_name North-LST-1 --max_offset 5.0
```

and getting the following issue:
```
....
INFO::psf_analysis(l93)::readSimtelFile::Reading SimtelFile /workdir/external/output/simtools-files/validate_optics/ray-tracing/photons-North-LST-1-d10.0-za20.0-off3.250_validate_optics.lis
Traceback (most recent call last):
  File "applications/validate_optics.py", line 161, in <module>
    ray.analyze(force=True)
  File "/workdir/external/gammasim-tools/simtools/ray_tracing.py", line 262, in analyze
    image.readSimtelFile(photonsFile)
  File "/workdir/external/gammasim-tools/simtools/psf_analysis.py", line 97, in readSimtelFile
    self._processSimtelLine(line)
  File "/workdir/external/gammasim-tools/simtools/psf_analysis.py", line 153, in _processSimtelLine
    self.photonPosY.append(float(words[3]))
IndexError: list index out of range
```

Looking at the files, it looks it the last line is not complete?

```
tail validate_optics/ray-tracing/photons-North-LST-1-d10.0-za20.0-off3.250_validate_optics.lis
1 -1 160.3876 -29.4020 132.363 861.534 -93.250 93.795895 118 160.6951 -27.3666 0.0470 0.3107 17.4465  1 29.2198 -897.4512  1.0000 0.0000
1 -1 158.0612 -31.0807 386.850 -88.599 -93.250 93.787307 141 158.5404 -31.3829 0.0732 -0.0461 4.9435  1 -46.2940 97.8355  1.0000 0.0000
1 -1 166.7878 -24.0425 668.916 811.142 -93.250 93.719388 173 168.3302 -22.3615 0.2355 0.2567 19.2040  1 -491.0270 -740.9850  1.0000 0.0000
1 -1 160.0647 -29.8182 -423.432 -203.811 -93.250 93.810025 58 158.6181 -30.0299 -0.2209 -0.0323 12.5828  1 777.0213 60.4858  1.0000 0.0000
1 -1 162.1468 -31.4188 723.002 -37.448 -93.250 93.772839 167 163.4238 -31.7546 0.1950 -0.0513 11.3976  1 -382.4839 111.7678  1.0000 0.0000
1 -1 166.3973 -28.1580 911.887 463.473 -93.250 93.748315 182 168.3555 -27.4052 0.2990 0.1149 17.7601  1 -668.7516 -349.2135  1.0000 0.0000
1 -1 160.2566 -28.6675 376.350 650.102 -93.250 93.785432 131 161.0392 -27.2501 0.1195 0.2164 13.8843  1 -173.5172 -633.1371  1.0000 0.0000
1 -1 160.0152 -29.4735 154.415 846.217 -93.250 93.797980 118 160.3686 -27.4852 0.0539 0.3036 17.1350  1 9.3306 -877.4361  1.0000 0.0000
1 -1 172.9610 -35.3542 1149.257 -183.167 -93.250 93.682482 194 175.1894 -36.2327 0.3402 -0.1341 20.0873  1 -777.4201 339.2801  1.0000 0.0000
1 -1 157.9733 -30.6663 19.375 -566.275 -93.250 93.795808 96 157.3896 -31.9130 -%
```

Log file from sim_telarray for this off-axis bin looks different than the others, ends with 
```
tail validate_optics/ray-tracing/log-North-LST-1-d10.0-za20.0-off3.250_validate_optics.log
Section 'transmission':
    ATMOSPHERIC_TRANSMISSION
                      Text     1023
                      Initial:   hess_atmo_trans.dat
                      Current:   atm_trans_2147_1_3_0_0_0.dat
Camera 1 by default requires 3 pixels per trigger group.
Reading setup for telescope 1 camera from file camera_CTA-LST-234_analogsum21_v2020-04-14.dat
Pixel type 1 has a hexagonal (flat y) funnel onto a circular visible cathode.
Reading funnel angle efficiencies for telescope 1 from CTA-LST_lightguide_eff_2020-04-12_average.dat
Table with 51 rows has been read from file CTA-LST_lightguide_eff_2020-04-12_average.dat
```

Could not see any problem with running sim_telarray, log file attached.
[log-North-LST-1-d10.0-za20.0-off3.250_validate_optics.log.gz](https://github.com/gammasim/gammasim-tools/files/5336312/log-North-LST-1-d10.0-za20.0-off3.250_validate_optics.log.gz)

**Comment by GernotMaier** [comment]
Hmm, removed all output files, tried it again and it works without problems. Not sure what went wrong.

Is there an option to run an application in a way that it overwrites all existing results? It seems that validate_optics is not overwriting previous ray-tracing results (maybe add an overwrite option?).

Was again hoping to have a break, as the documentation say 'Runtime about 50 min.'. The example was done after 2m30s! (I don't complain).

Is 'offset (deg)' a clear name for an axis title? Offset relative to what? Maybe use 'distance to centre of FOV' or something similar.

Otherwise very nice, I could run for the first time the ray tracing without problems and have an LST PSF curve done in 3 min!!

I start understanding the directory structure of the output. Please add it to the documentation, so that it is easier in the beginning (structure is good!). Maybe mention as well that one can always find the configuration files in there.

**Comment by RaulRPrado** [comment]
> Hmm, removed all output files, tried it again and it works without problems. Not sure what went wrong.
> 
> Is there an option to run an application in a way that it overwrites all existing results? It seems that validate_optics is not overwriting previous ray-tracing results (maybe add an overwrite option?).

Not at the application level, only at the library level. I will add a command line arg for that. Thanks.

> Was again hoping to have a break, as the documentation say 'Runtime about 50 min.'. The example was done after 2m30s! (I don't complain).

Not sure why the runtime is so different. I'll investigate it later.

> Is 'offset (deg)' a clear name for an axis title? Offset relative to what? Maybe use 'distance to centre of FOV' or something similar.

Or 'off-axis angle'?

**Comment by GernotMaier** [comment]
Off-axis angle is good.

**Comment by RaulRPrado** [comment]
Done
