### ISSUE TITLE
Creation of a telescope_mirrors module

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#8]
Following the plan of creating sub-modules for the telescope_model module, a module for dealing with mirrors is needed. All the functions related to handling the mirror list and get mirror parameters in TelescopeModel should be implemented in a new class Mirrors or TelescopeMirrors.

**Comment by RaulRPrado** [comment]
@orelgueta , I created a mirrors module, very similar to the camera one. By now it's very simple, with only few functionalities that are needed by the single mirror ray tracing stuff.
You probably have a lot of code to be added to this module, e.g. the plotting mirror layout routine.
So whenever you decide to do it, keep in mind that the module already exist.

It was implemented in develop branch but I'll do a pull request soon.

**Comment by orelgueta** [comment]
OK, thanks, once I add the mirror layout code, I will put it there.
