### ISSUE TITLE
Testing validate_camera_fov.py

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#84]
Works!

Looking at the plot, different items:

- is the coordinate system x_pix/y_pix in the bottom right rotated correctly? I would have expected that it aligns with the bin edges.
- minor option request: switch off plotting of pixel numbers, plot all, plot first N (could probably be handled with one command line parameter)

![validate_camera_fov_North-LST-1_pixelLayout](https://user-images.githubusercontent.com/14001688/95293590-00591a00-0874-11eb-89cb-1cdd257852e1.png)

**Comment by orelgueta** [comment]
The rotation of the camera is wrong, not sure what happened there, will check soon.

> minor option request: switch off plotting of pixel numbers, plot all, plot first N (could probably be handled with one command line parameter)

Adding all pixels (or any number above 99) is a little ugly cause you quickly run into space problems within the pixel (especially in the thousands). I can give it a try again, but it might not work out.
