### ISSUE TITLE
Interplation in camera efficiencies

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#87]
Calculating camera efficiencies for prod4:

```
python applications/validate_camera_efficiency.py --tel_name South-SST-D --model_version prod4
```

Result in many errors in the log file:

```
cat camera-efficiency-South-SST-D-za20.0_validate_camera_efficiency.log
Secondary mirror optics to account for two reflections.
Shadowing by secondary mirror is not accounted for.
Read atmospheric transmission data from file atm_trans_2200_1_3_0_0_0.dat
Got 800 wavelength intervals for 41 heights starting at 2.200 km
Read atmospheric transmission data from file atm_trans_2150_1_10_0_0_2150.dat
Got 800 wavelength intervals for 41 heights starting at 2.150 km
Table for 2-D interpolation with 801 rows and 9 columns has been read from file ref_astri-2d_2018-01-17.dat
Reading quantum efficiency data from file PDE_V_4.4V_LVR5_ext.txt
Reading mirror reflectivity data from file ref_astri-2d_2018-01-17.dat
Using only upper envelope of 2-D reflectivity table.
Reflectivity squared to account for secondary mirror.
Implied perfect reflectivity from 200 to 999 nm
Reflectivity squared to account for secondary mirror.
Implied perfect quantum efficiency from 200 to 999 nm
Using only upper envelope of 2-D reflectivity table.
Reflectivity squared to account for secondary mirror.
Table with 4 rows has been read from file funnel_perfect.dat
Table with 381 rows has been read from file hess_mirrors.dat
Table with 50 rows has been read from file atmprof1.dat
Table with 438 rows has been read from file Benn_LaPalma_sky_converted.lis
Error in line 12 of file transmission_astri_window_new.dat (expcting 2 values, found 0).
Warning: Quantum efficiency not dropping to zero for long wavelengths.
Interpolation error.
Interpolation error.
Interpolation error.
Interpolation error.
Interpolation error.
...
```

**Comment by RaulRPrado** [comment]
The "Error in line 12 ..." was a bug. The testeff cannot handle 2D transmission tables, so we have to replace it by the old 1D. The bug was that the South-SST-D wasn't being identified as a ASTRI-like model. It's fixed on the master now (https://github.com/gammasim/gammasim-tools/commit/c96aa0c5b8ac6ae6230544087c69bc45e9ceab06)

The "Interpolation error." is a simtel message. We could report it to Konrad, although I'd assume he is already aware of it.

**Comment by GernotMaier** [comment]
I still see the error

```
Error in line 12 of file transmission_astri_window_new.dat (expcting 2 values, found 0).
```

I've confirmed that I've updated my local installation and that the change from c96aa0c is there.

**Comment by RaulRPrado** [comment]
That is weird. It works fine here. Try this in your gammasim-tools directory:
grep "South-SST-D" simtools/model/telescope_model.py

You should get:        return self.telescopeName in ['SST-2M-ASTRI', 'SST', 'South-SST-D']

If not, it's a github version problem.

BTW, are you using South-SST-D or South-SST-1? It should be D.

**Comment by GernotMaier** [comment]
```
 grep "South-SST-D" simtools/model/telescope_model.py
        return self.telescopeName in ['SST-2M-ASTRI', 'SST', 'South-SST-D']
```

and I use

```
python applications/validate_camera_efficiency.py --tel_name South-SST-D --model_version prod4
```

Would it be possible to print out in the error message the full path of the file?

Is line 12 in transmission_astri_window_new.dat actually line 12 or the 12th line without a comment. Line 12 looks like:

```
ANGLE=             12               16               20               24               28               32               36               40               44               48               52               56               60               64               68               72               76               80
```

**Comment by RaulRPrado** [comment]
This is the log file from simtel, not ours.
With simtools working fine, the file should be transmission_astri_window_average.dat, not *_new.dat.

I will keep doing more tests to understand this better. By now,, I have no idea.

**Comment by RaulRPrado** [comment]
This is fixed at the develop branch. I will do a PR later with a collection of issue fixes.
May we close this, @GernotMaier ?

**Comment by GernotMaier** [comment]
Fixed. closing it.
