### ISSUE TITLE
Missing file in camera efficiency calculation

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#88]
Get the following error when running

```
 python applications/validate_camera_efficiency.py --tel_name South-SST-1 --model_version prod4
```

ERROR::config(l196)::findFile::File camera_CHEC-S_x9r.dat could not be found in /workdir/external/output/simtools-files/validate_camera_efficiency/model

Is this related to not using the data base but the configuration files from the gitlab?

**Comment by GernotMaier** [comment]
Similar for Flashcam one file is missing:

ERROR::config(l196)::findFile::File camera_CTA-MST-FlashCam_patch3_digitalsum9_neweff2.dat could not be found in /workdir/external/output/simtools-files/validate_camera_efficiency/model

**Comment by RaulRPrado** [comment]
Is /workdir/external/output/simtools-files/validate_camera_efficiency/model in your modelFilesLocation list at the config file?

The model directory in the simtools output is meant for the model related files that are created on the fly, like the simtel cfg files.
They do not contain all the model files that simtel needs. This should still be in another directory, containing the gitlab files. 
 
Note that we are still not writing all the tabulated data from the DB yet. We will do it soon but I'm not sure if they will go to the model output directory.

**Comment by GernotMaier** [comment]
Yes, /workdir/external/output/simtools-files/validate_camera_efficiency/model is my model directory.

But does that mean that all efficiencies are applied when using the application? Can I trust the result?

**Comment by RaulRPrado** [comment]
> Yes, /workdir/external/output/simtools-files/validate_camera_efficiency/model is my model directory.

Ok. So change it to the directory with the files from gitlab.

> But does that mean that all efficiencies are applied when using the application? Can I trust the result?

I don't get it. What the location of the model files have to do with that?

Another point: I'm not sure what is the status of South-SST-1 in the DB. I wouldn't be surprised if it's still incomplete. But @orelgueta give the final answer.

**Comment by GernotMaier** [comment]
These are my model file locations:

```
modelFilesLocations: [
  /workdir/external/simulation-model-description/configReports/,
  /workdir/external/simulation-model-description/datFiles/,
  /workdir/external/verification-process/dataFromInstrumentTeams/
]
```

simulation-model-description is the gitlab directory

**Comment by RaulRPrado** [comment]
Ah ok. It should work then. I'll have another look.

**Comment by orelgueta** [comment]
> Note that we are still not writing all the tabulated data from the DB yet. We will do it soon but I'm not sure if they will go to the model output directory.

Wait, that's not accurate. We do write all **model** tabulated data into the DB. What's missing are additional files we received from the instrument teams. Those are used sometimes in derivation applications (and I am not sure how/where to write them into the DB yet).
However, the two files Gernot mentioned "camera_CHEC-S_x9r.dat" and "camera_CTA-MST-FlashCam_patch3_digitalsum9_neweff2.dat" are in the simulation model GitLab repo, so the application should find it.

> Another point: I'm not sure what is the status of South-SST-1 in the DB. I wouldn't be surprised if it's still incomplete. But @orelgueta give the final answer.

Not sure why it wouldn't be complete, it should be. Did I forget something?

**Comment by GernotMaier** [comment]
I think we can close this issue, as it was related to my local setup (long time ago...)

**Comment by orelgueta** [comment]
OK, closing.
