### ISSUE TITLE
error catching for non-existing telescope model

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#98]
(on the develop branch)

I guess in the following the telescope model did not exist:

```
 python applications/validate_camera_fov.py --tel_name South-SST-1 --model_version prod5
Traceback (most recent call last):
  File "/workdir/external/gammasim-tools/applications/validate_camera_fov.py", line 90, in <module>
    telModel = TelescopeModel(
  File "/workdir/external/gammasim-tools/simtools/model/telescope_model.py", line 101, in __init__
    self._loadParametersFromDB()
  File "/workdir/external/gammasim-tools/simtools/model/telescope_model.py", line 224, in _loadParametersFromDB
    self._parameters = db.getModelParameters(
  File "/workdir/external/gammasim-tools/simtools/db_handler.py", line 236, in getModelParameters
    return self._getModelParametersYaml(telescopeName, version, onlyApplicable)
  File "/workdir/external/gammasim-tools/simtools/db_handler.py", line 260, in _getModelParametersYaml
    _telNameConverted = names.convertTelescopeNameToYaml(_telNameValidated)
  File "/workdir/external/gammasim-tools/simtools/util/names.py", line 290, in convertTelescopeNameToYaml
    raise ValueError('Telescope name {} could not be converted to yml names'.format(name))
ValueError: Telescope name South-SST-1 could not be converted to yml names
```

Do we want those python error or shouldn't there be a reasonable error catching?

The error message is probably informative for developers, but I would imaging that it is hard to understand what '...could not be converted to yml names' means. Does it mean that there is no South-SST-1 in the model?

**Comment by RaulRPrado** [comment]
You are right, this telescope is not available in the model and the error should be something more generic and clear.

**Comment by orelgueta** [comment]
Now the error you would get for providing a non-existent telescope would be
```
ValueError: ('The following query returned zero results! Check the input data and rerun.\n', {'Telescope': 'South-SST-1', 'Version': '2020-06-28'})
```

Do you think this is a clearer error? In this case it does not tell you whether the issue is with the version or the telescope, but separating the two would mean running additional queries just for the error message. The other option is to keep a list of allowed telescope names which we sort of decided earlier this week not to do. Therefore, I suggest we live with the current error and close this issue.

**Comment by GernotMaier** [comment]
Agree with this. I am closing the issue.
